---
permalink: windows/concept_preparing_to_upgrade_snapmanager_for_oracle.html 
sidebar: sidebar 
keywords: environment, software, hardware, browser, database, operating, system, preparing 
summary: 'L"ambiente in cui si desidera aggiornare SnapManager deve soddisfare i requisiti specifici di software, hardware, browser, database e sistema operativo. Per informazioni aggiornate sui requisiti, consulta la matrice di interoperabilità.' 
---
= Preparazione all'aggiornamento di SnapManager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'ambiente in cui si desidera aggiornare SnapManager deve soddisfare i requisiti specifici di software, hardware, browser, database e sistema operativo. Per informazioni aggiornate sui requisiti, consulta la matrice di interoperabilità.

Prima di eseguire l'aggiornamento, assicurarsi di eseguire le seguenti attività:

* Completare le attività di preinstallazione richieste.
* Scarica il pacchetto di installazione più recente di SnapManager per Oracle.
* Installare e configurare la versione appropriata di SnapDrive per Windows su tutti gli host di destinazione.
* Creare un backup del database repository SnapManager per Oracle esistente.


http://support.netapp.com/NOW/products/interoperability/["Matrice di interoperabilità: support.netapp.com/NOW/products/interoperability"]
