---
permalink: windows/concept_protecting_database_backups_by_using_post_scripts.html 
sidebar: sidebar 
keywords: enable, protect, database, backup, postscript, snapmirror, snapvault, relationship, postscript, cli, gui 
summary: 'SnapManager consente di proteggere i backup dei database utilizzando postscript quando viene stabilita una relazione SnapMirror o SnapVault tra i sistemi di storage primario e secondario. È possibile utilizzare i postscript predefiniti per l"attività di post-elaborazione dell"operazione di backup sia dall"interfaccia utente di SnapManager che dalla GUI.' 
---
= Protezione dei backup dei database mediante postscript
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager consente di proteggere i backup dei database utilizzando postscript quando viene stabilita una relazione SnapMirror o SnapVault tra i sistemi di storage primario e secondario. È possibile utilizzare i postscript predefiniti per l'attività di post-elaborazione dell'operazione di backup sia dall'interfaccia utente di SnapManager che dalla GUI.

È possibile utilizzare i seguenti postscript predefiniti disponibili in directory_installazione_predefinita/backup/creazione/post:

* SnapMirror postscript, Mirror_the_backup.cmd se si utilizza Data ONTAP in 7-Mode
* il file postscript di SnapVault, Vault_the_backup.cmd se si utilizza Data ONTAP in modalità 7
* SnapMirror postscript, Mirror_the_backup_cDOT.cmd se si utilizza Clustered Data ONTAP
* il file postscript di SnapVault, Vault_the_backup_cDOT.cmd se si utilizza Clustered Data ONTAP


Per ulteriori informazioni, consultare la pagina readme.txt disponibile all'indirizzo directory_installazione_predefinita.

SnapManager 3.1 o versioni precedenti fornisce script di pre-elaborazione o post-elaborazione solo per operazioni di cloni. SnapManager 3.2 o versione successiva fornisce script di pre-elaborazione e post-elaborazione per le operazioni di backup e ripristino. È possibile utilizzare questi script per eseguirli prima o dopo le operazioni di backup o ripristino.


NOTE: Gli script sono forniti solo a scopo di riferimento. Sono stati testati con SnapDrive 7.0 per Windows o versioni successive, ma potrebbero non funzionare in tutti gli ambienti. È necessario personalizzare gli script in base ai requisiti di protezione secondari. Gli script non funzionano con le versioni di SnapDrive precedenti alla 6.2.
