---
permalink: windows/concept_preinstallation_tasks.html 
sidebar: sidebar 
keywords: install, snapmanager, oracle, environment, preinstallation, task 
summary: 'Prima di installare SnapManager per Oracle, è necessario eseguire alcune attività aggiuntive per configurare l"ambiente. Le attività da eseguire dipendono dal sistema operativo, dai componenti Oracle e dalla versione del database che si desidera utilizzare.' 
---
= Attività di preinstallazione
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di installare SnapManager per Oracle, è necessario eseguire alcune attività aggiuntive per configurare l'ambiente. Le attività da eseguire dipendono dal sistema operativo, dai componenti Oracle e dalla versione del database che si desidera utilizzare.

* Installare il sistema operativo concesso in licenza con le patch appropriate.
* Impostare le lingue del sistema operativo e del database Oracle sull'inglese.
+
Ad esempio, per impostare la lingua del database Oracle sull'inglese, assegnare NLS_LANG = AMERICAN_AMERICA.WE8MSWIN1252. Per ulteriori informazioni su come impostare la lingua, consultare la sezione _risoluzione dei problemi di SnapManager per Oracle_.

* Installare Oracle Recovery Manager (RMAN) se si desidera utilizzare RMAN con SnapManager per Oracle.
* Installare Data ONTAP con le licenze abilitate per SnapRestore e i protocolli supportati come Fibre Channel (FC) e iSCSI (Internet Small computer System Interface) su tutti i sistemi storage.
* Installare le seguenti patch Oracle, se si utilizzano database Oracle 11.2.0.2 e 11.2.0.3:
+
** 13413167 per Windows a 32 bit
** 13555974 per Windows a 64 bit




*Informazioni correlate*

xref:reference_troubleshooting_snapmanager.adoc[Risoluzione dei problemi di SnapManager]

http://support.netapp.com/NOW/products/interoperability/["Matrice di interoperabilità NetApp: support.netapp.com/NOW/products/interoperability"]

http://media.netapp.com/documents/tr-3761.pdf["Best practice per SnapManager per Oracle: media.netapp.com/documents/tr-3761.pdf"]
