---
permalink: windows/reference_the_smosmsaprepository_delete_command.html 
sidebar: sidebar 
keywords: command, delete, repository, store, database, associate, credential, delete, smo 
summary: Questo comando elimina un repository utilizzato per memorizzare i profili di database e le credenziali associate. È possibile eliminare un repository solo se non sono presenti profili nel repository. 
---
= Il comando smo repository delete
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Questo comando elimina un repository utilizzato per memorizzare i profili di database e le credenziali associate. È possibile eliminare un repository solo se non sono presenti profili nel repository.



== Sintassi

[listing]
----

        smo repository delete
-repository
-port repo_port
-dbname repo_service_name
-host repo_host
-login -username repo_username
[-force] [-noprompt]
[-quiet | -verbose]
----


== Parametri

* *-repository*
+
Le opzioni che seguono -repository specificano i dettagli del database per il repository.

* *-port repo_port*
+
Specifica il numero di porta TCP utilizzato per accedere al database in cui è memorizzato il repository.

* *-dbname repo_service_name*
+
Specifica il nome del database in cui è memorizzato il repository. Utilizzare il nome globale o il SID.

* *-host repo_host*
+
Specifica il nome o l'indirizzo IP del computer host su cui viene eseguito il database del repository.

* *-login*
+
Avvia i dettagli di accesso al repository.

* *-nome utente repo_nome utente*
+
Specifica il nome utente necessario per accedere al database in cui è memorizzato il repository.

* *-force*
+
Tenta di forzare l'eliminazione del repository, anche in caso di operazioni incomplete. In caso di operazioni incomplete, SnapManager visualizza un messaggio che chiede se si è sicuri di voler eliminare il repository.

* *-noprompt*
+
Non richiede prima di eliminare il repository. L'opzione -noprompt consente di evitare la visualizzazione del prompt, semplificando l'eliminazione dei repository mediante uno script.

* *-quiet*
+
Visualizza solo i messaggi di errore sulla console. L'impostazione predefinita prevede la visualizzazione dei messaggi di errore e di avviso.

* *-dettagliato*
+
Visualizza messaggi di errore, di avviso e informativi sulla console.





== Esempio di comando

Nell'esempio seguente viene eliminato il repository nel database SALESDB.

[listing]
----
smo repository delete -repository -port 1521 -dbname smorep
-host nila -login -username smofresno -force -verbose
This command will delete repository "smofresno@smorep/nila".
Any resources maintained by the repository must be cleaned up manually.
This may include snapshots, mounted backups, and clones.
Are you sure you wish to proceed (Y/N)?Y
[ INFO] SMO-09201: Dropping existing schema as smofresno
  on jdbc:oracle:thin:@//nila:1521/smorep.
[ INFO] SMO-13048: Repository Delete Operation Status: SUCCESS
[ INFO] SMO-13049: Elapsed Time: 0:00:06.372
[ INFO] SMO-20010: Synchronizing mapping for profiles in
   repository "smofresno@smorep/nila:1521".
[ WARN] SMO-20029: No repository schema exists in "smofresno@smorep/nila:1521".
 Deleting all profile mappings for this repository.
[ INFO] SMO-20012: Deleted stale mapping for profile "TESTPASS".
----