---
permalink: windows/reference_running_multiple_parallel_operations_fail_in_snapmanager.html 
sidebar: sidebar 
keywords: run, multiple, parallel, operation, fail, database, storage, system, igroup, lun 
summary: 'Quando si eseguono più operazioni parallele su database separati che risiedono sullo stesso sistema di storage, l"igroup per le LUN associate a entrambi i database potrebbe essere cancellato a causa di una delle operazioni. In seguito, se l"altra operazione tenta di utilizzare l"igroup cancellato, SnapManager visualizza un messaggio di errore.' 
---
= L'esecuzione di più operazioni parallele non riesce in SnapManager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando si eseguono più operazioni parallele su database separati che risiedono sullo stesso sistema di storage, l'igroup per le LUN associate a entrambi i database potrebbe essere cancellato a causa di una delle operazioni. In seguito, se l'altra operazione tenta di utilizzare l'igroup cancellato, SnapManager visualizza un messaggio di errore.

Ad esempio, se si eseguono le operazioni di eliminazione e creazione del backup su database diversi quasi contemporaneamente, l'operazione di creazione del backup non riesce. I seguenti passaggi sequenziali mostrano cosa accade quando si eseguono operazioni di eliminazione e creazione di backup su database diversi quasi contemporaneamente.

. Eseguire il comando di eliminazione del backup.
. Eseguire il comando di creazione del backup.
. Il comando backup create identifica l'igroup già esistente e utilizza lo stesso igroup per la mappatura del LUN.
. Il comando di eliminazione del backup elimina il LUN di backup, mappato allo stesso igroup.
. Il comando di cancellazione del backup elimina quindi l'igroup perché non vi sono LUN associati all'igroup.
. Il comando backup create crea il backup e tenta di eseguire il mapping all'igroup che non esiste, quindi l'operazione non riesce.


*Cosa fare*

È necessario creare igroup per ogni sistema storage utilizzato dal database utilizzando il seguente comando: Sdcli igroup create
