---
permalink: windows/reference_the_smosmsap_notification_set_command.html 
sidebar: sidebar 
keywords: notification, set, command, configure, mail, server, smo 
summary: Per configurare il server di posta, è possibile utilizzare il comando set di notifiche. 
---
= Il comando smo notification set
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per configurare il server di posta, è possibile utilizzare il comando set di notifiche.



== Sintassi

[listing]
----

        smo notification set
-sender-email email_address
-mailhost mailhost
-mailport mailport
[-authentication
-username username
-password password]
-repository
-dbname repo_service_name
-port repo_port]
-host repo_host
-login -username repo_username
[-quiet | -verbose]
----


== Parametri

* *-sender-email email_address*
+
Specifica l'indirizzo e-mail del mittente da cui vengono inviati gli avvisi e-mail. Da SnapManager 3.2 per Oracle, è possibile includere un trattino (-) specificando il nome di dominio dell'indirizzo e-mail. Ad esempio, è possibile specificare l'indirizzo e-mail del mittente come -sender-email07lbfmdatacenter@continental-corporation.com.

* *-mailhost mailhost*
+
Specifica il nome o l'indirizzo IP del server host che gestisce le notifiche e-mail.

* *-mailport mailport*
+
Specifica il numero di porta del server di posta.

* *-authentication -nome utente -password password*
+
Specifica i dettagli di autenticazione per l'indirizzo e-mail. Specificare il nome utente e la password.

* *-repository*
+
Specifica i dettagli del database del repository.

* *-port repo_port*
+
Specifica il numero di porta TCP (Transmission Control Protocol) utilizzato per accedere al database del repository.

* *-dbname repo_service_name*
+
Specifica il nome del database del repository. È possibile utilizzare il nome globale o l'identificatore di sistema.

* *-host repo_host*
+
Specifica il nome o l'indirizzo IP dell'host in cui risiede il database del repository.

* *-login*
+
Specifica i dettagli di accesso al repository. Questa opzione è facoltativa. Se non viene specificato, SnapManager passa automaticamente alla modalità di connessione autenticazione del sistema operativo.

* *-nome utente repo_nome utente*
+
Specifica il nome utente richiesto per accedere al database del repository.

* *-quiet*
+
Visualizza solo i messaggi di errore nella console. L'impostazione predefinita prevede la visualizzazione dei messaggi di errore e di avviso.

* *-dettagliato*
+
Visualizza messaggi di errore, di avviso e informativi nella console.





== Esempio

Nell'esempio seguente viene configurato il server di posta:

[listing]
----
smo notification set -sender-email admin@org.com -mailhost hostname.org.com -mailport 25 authentication -username davis -password davis -repository -port 1521 -dbname SMOREPO -host hotspur
-login -username grabal21 -verbose
----