---
permalink: windows/reference_the_smosmsapbackup_mount_command.html 
sidebar: sidebar 
keywords: run, backup, mount, command, recover, operation, external 
summary: 'È possibile eseguire il comando di montaggio del backup per montare un backup al fine di eseguire un"operazione di ripristino utilizzando uno strumento esterno.' 
---
= Il comando di montaggio del backup smo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile eseguire il comando di montaggio del backup per montare un backup al fine di eseguire un'operazione di ripristino utilizzando uno strumento esterno.



== Sintassi

[listing]
----

        smo backup mount
-profile profile_name
[-label label \[-data \| -archivelogs\] \| \[-id id\]
[-host  host]

\[-dump\]
[-quiet | -verbose]
----


== Parametri

* *-profile_name*
+
Specifica il profilo associato al backup che si desidera montare. Il profilo contiene l'identificatore del database e altre informazioni del database.

* *-id guid*
+
Consente di montare il backup con il GUID specificato. Il GUID viene generato da SnapManager quando si crea un backup. È possibile utilizzare il comando smo backup list per visualizzare il GUID per ciascun backup.

* etichetta **
+
Consente di montare il backup con l'etichetta specificata.

* *-dati*
+
Specifica i file di dati.

* *-archivelogs*
+
Specifica i file di log dell'archivio.

* *-host host*
+
Specifica l'host su cui si desidera montare il backup.

* *-dump*
+
Raccoglie i file dump dopo l'operazione di montaggio riuscita o non riuscita.

* *-quiet*
+
Visualizza solo i messaggi di errore nella console. L'impostazione predefinita prevede la visualizzazione dei messaggi di errore e di avviso.

* *-dettagliato*
+
Visualizza messaggi di errore, di avviso e informativi nella console.




NOTE: Utilizzare questo comando solo se si utilizza uno strumento esterno come Oracle Recovery Manager (RMAN). SnapManager gestisce automaticamente il montaggio dei backup se si utilizza il comando smo backup restore per ripristinare il backup. Questo comando visualizza un elenco che mostra i percorsi in cui sono state montate le copie Snapshot. Questo elenco viene visualizzato solo quando viene specificata l'opzione -verbose.



== Esempio

Nell'esempio seguente viene montato il backup:

[listing]
----
smo backup mount -profile SALES1 -label full_backup_sales_May -verbose
[INFO ]: SMO-13051: Process PID=6852
[INFO ]: SMO-13036: Starting operation Backup Mount on host hadley.domain.private
[INFO ]: SMO-13036: Starting operation Backup Mount on host hadley.domain.private
[INFO ]: SMO-13046: Operation GUID 8abc01573883daf0013883daf5ac0001 starting on Profile FAS_P1
[INFO ]: SD-00025: Beginning to connect filesystem(s) [I:\] from snapshot smo_fas_p1_fasdb_d_h_2_8abc0157388344bc01388344c2d50001_0.
[INFO ]: SD-00016: Discovering storage resources for C:\SnapManager_auto_mounts\I-2012071400592328_0.
[INFO ]: SD-00017: Finished storage discovery for C:\SnapManager_auto_mounts\I-2012071400592328_0
[INFO ]: SD-00026: Finished connecting filesystem(s) [I:\] from snapshot smo_fas_p1_fasdb_d_h_2_8abc0157388344bc01388344c2d50001_0.
[INFO ]: SD-00025: Beginning to connect filesystem(s) [H:\] from snapshot smo_fas_p1_fasdb_d_h_1_8abc0157388344bc01388344c2d50001_0.
[INFO ]: SD-00016: Discovering storage resources for C:\SnapManager_auto_mounts\H-2012071400592312_0.
[INFO ]: SD-00017: Finished storage discovery for C:\SnapManager_auto_mounts\H-2012071400592312_0.
[INFO ]: SD-00026: Finished connecting filesystem(s) [H:\] from snapshot smo_fas_p1_fasdb_d_h_1_8abc0157388344bc01388344c2d50001_0.
[INFO ]: SMO-13048: Backup Mount Operation Status: SUCCESS
[INFO ]: SMO-13049: Elapsed Time: 0:19:05.620
----
*Informazioni correlate*

xref:task_mounting_backups.adoc[Montaggio dei backup]
