---
permalink: windows/reference_the_smosmsapcredential_delete_command.html 
sidebar: sidebar 
keywords: command, delete, credentials, particular, secured, resource, smo 
summary: 'Questo comando elimina le credenziali dell"utente per una particolare risorsa protetta.' 
---
= Il comando smo credential delete
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Questo comando elimina le credenziali dell'utente per una particolare risorsa protetta.



== Sintassi

[listing]
----

        smo credential delete
\[-host -name host_name
-username username\] \|
[-repository
-dbname repo_service_name
-host repo_host
-login -username repo_username
-port repo_port\] \|
\[-profile
-name profile_name\]
[-quiet | -verbose]
----


== Parametri

* *-host hostname*
+
Specifica il nome del server host su cui è in esecuzione SnapManager.

+
Il parametro -host include le seguenti opzioni:

+
** -Name host_name: Specifica il nome dell'host per il quale si desidera eliminare la password.
** -Nome_utente: Specifica il nome utente sull'host.


* *-repository -dbname*
+
Specifica il nome del database in cui è memorizzato il profilo. Utilizzare il nome globale o il SID.

+
Il parametro -repository include le seguenti opzioni:

+
** -Dbnamerepo_service_name: Specifica il nome del database che memorizza il profilo. Utilizzare il nome globale o il SID.
** -Host repo_host: Specifica il nome o l'indirizzo IP del server host su cui viene eseguito il database del repository.
** -Login-Username repo_Username: Specifica il nome utente necessario per accedere al database che memorizza il repository.
** -Port repo_port: Specifica il numero di porta TCP utilizzato per accedere al database che memorizza il repository.


* *-profile -name profile_name*
+
Specifica il profilo a cui è associato il database.

+
Il parametro -profile include la seguente opzione:

+
** -Name profilename: Specifica il nome del profilo per il quale si desidera eliminare la password.


* *-quiet*
+
Visualizza solo i messaggi di errore sulla console. L'impostazione predefinita prevede la visualizzazione dei messaggi di errore e di avviso.

* *-dettagliato*
+
Visualizza messaggi di errore, di avviso e informativi sulla console.





== Esempio di comando

Questo esempio elimina le credenziali del profilo.

[listing]
----
smo credential delete -profile -name user1 -verbose
----
[listing]
----
SMO-20022 [INFO ]: Deleted credentials and repository mapping
 for profile "user1" in user credentials for "user1".
----
Questo esempio elimina le credenziali del repository.

[listing]
----
smo credential delete -repository -dbname SMOREPO -host Host2
-login -username user1 -port 1521
----
[listing]
----
SMO-20023 [INFO ]: Deleted repository credentials for "user1@SMOREPO/wasp:1521"
and associated profile mappings in user credentials for "user1".
----
Questo esempio elimina le credenziali dell'host.

[listing]
----
smo credential delete -host -name Host2
----
[listing]
----
SMO-20033 [INFO ]: Deleted host credentials for "Host2" in user credentials for "user1".
----
*Informazioni correlate*

xref:task_deleting_credentials_for_individual_resources.adoc[Eliminazione delle credenziali per le singole risorse]
