---
permalink: windows/reference_the_smosmsap_password_reset_command.html 
sidebar: sidebar 
keywords: run, password, reset, command, profile, smo 
summary: È possibile eseguire il comando di reimpostazione della password per reimpostare la password di un profilo. 
---
= Il comando di reimpostazione della password smo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile eseguire il comando di reimpostazione della password per reimpostare la password di un profilo.



== Sintassi

[listing]
----

        smo password reset
-profile profile
\[-profile-password profile_password\]
\[-repository-hostadmin-password repository_hostadmin_password\]
[-quiet | -verbose]
----


== Parametri

* *-profilo profilo*
+
Specifica il nome del profilo per cui si desidera reimpostare la password.

* *-profile-password profile_password*
+
Specifica la nuova password per il profilo.

* *-repository-hostadmin-password admin_password*
+
Specifica la credenziale dell'utente autorizzato con privilegio di amministratore locale per il database del repository.

* *-quiet*
+
Visualizza solo i messaggi di errore nella console. L'impostazione predefinita prevede la visualizzazione dei messaggi di errore e di avviso.

* *-dettagliato*
+
Visualizza messaggi di errore, di avviso e informativi nella console.


