---
permalink: windows/reference_the_smosmsapoperation_list_command.html 
sidebar: sidebar 
keywords: command, list, summary, information, operation, record, profile, smo 
summary: Questo comando elenca le informazioni di riepilogo di tutte le operazioni registrate in base a un profilo specifico. 
---
= Il comando smo Operation list
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Questo comando elenca le informazioni di riepilogo di tutte le operazioni registrate in base a un profilo specifico.



== Sintassi

[listing]
----

        smo operation list
-profile profile_name
\[-delimiter character\]
\[-quiet \| -verbose\]
----


== Parametri

* *-profile_name*
+
Specifica il nome del profilo. Questo nome può contenere fino a 30 caratteri e deve essere univoco all'interno dell'host.

* carattere *-delimitatore*
+
(Facoltativo) quando viene specificato questo parametro, il comando elenca ogni riga su una riga separata e gli attributi in tale riga sono separati dal carattere specificato.

* *-quiet*
+
(Facoltativo) Visualizza solo i messaggi di errore sulla console. L'impostazione predefinita prevede la visualizzazione dei messaggi di errore e di avviso.

* *-dettagliato*
+
(Facoltativo) Visualizza messaggi di errore, di avviso e informativi sulla console.





== Esempio di comando

Nell'esempio riportato di seguito sono elencate le informazioni di riepilogo di tutte le operazioni registrate in relazione al profilo specificato.

[listing]
----
smo operation list -profile myprofile
----
[listing]
----
Start Date Status Operation ID Type Host
-------------------- ---------- -------------------------------- ------------------ --
2007-07-16 16:03:57 SUCCESS 8abc01c813d0a1530113d0a15c5f0005 Profile Create Host3
2007-07-16 16:04:55 FAILED 8abc01c813d0a2370113d0a241230001 Backup Host3
2007-07-16 16:50:56 SUCCESS 8abc01c813d0cc580113d0cc60ad0001 Profile Update Host3
2007-07-30 15:44:30 SUCCESS 8abc01c81418a88e011418a8973e0001 Remove Backup Host3
2007-08-10 14:31:27 SUCCESS 8abc01c814510ba20114510bac320001 Backup Host3
2007-08-10 14:34:43 SUCCESS 8abc01c814510e9f0114510ea98f0001 Mount Host3
2007-08-10 14:51:59 SUCCESS 8abc01c814511e6e0114511e78d40001 Unmount Host3
----
*Informazioni correlate*

xref:task_viewing_a_list_of_operations.adoc[Visualizzazione di un elenco di operazioni]
