---
permalink: windows/task_customizing_e_mail_subject_for_a_new_profile.html 
sidebar: sidebar 
keywords: customize, email, subject, new, profile, create, customizing 
summary: 'È possibile personalizzare l"oggetto dell"e-mail per il nuovo profilo al momento della creazione.' 
---
= Personalizzazione dell'oggetto dell'e-mail per un nuovo profilo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile personalizzare l'oggetto dell'e-mail per il nuovo profilo al momento della creazione.

Puoi personalizzare l'oggetto dell'email usando il modello{profile}_{nome-operazione}_{db-sid}_{db-host}_{data-inizio}_{data-fine}_{stato} o inserisci il tuo testo.

|===


| Nome della variabile | Descrizione | Valore di esempio 


 a| 
profilo
 a| 
Nome del profilo utilizzato per l'operazione del database
 a| 
PROF1



 a| 
nome-operazione
 a| 
Nome operazione database
 a| 
Backup, backup dei dati, backup dei dati e dei registri di archiviazione



 a| 
db-sid
 a| 
SID del database
 a| 
DB1



 a| 
db-host
 a| 
Nome del server host
 a| 
Host



 a| 
data di inizio
 a| 
Ora di inizio dell'operazione del database nel formato mmdd:hh:ss yyyy
 a| 
Aprile 27 21:00:45 PST 2012



 a| 
data di fine
 a| 
Ora di fine dell'operazione del database nel formato mmdd:hh:ss yyyy
 a| 
Aprile 27 21:10:45 PST 2012



 a| 
stato
 a| 
Stato operativo del database
 a| 
Successo

|===
Se non si fornisce alcun valore per le variabili, SnapManager visualizza il seguente messaggio di errore: Valori mancanti -subject.

. Immettere il seguente comando: smo profile create -profileprofile [-profile-passwordprofile_password] -repository-dbnamerepo_service_name-hostrepo_host-portrepo_port-login-username-username_username_username_name_db_host [-siddddb_name] [-{-nomesignesignub] [-nomesignub] [-nomesignub] [-nomesignub] [-{-nomesignub] [-nomesignub] [-} }-nomesignub] [-nomesignub] [-nomesignub] [-nomesignub] [-nomesignub] [-nomesignub] [-nomesignub]_-nomesignub] [-nomesignub-nomesignub]_nome_nome_] [-nomesignub] [-nomesignub] [-nomesignub] [-]

