---
permalink: windows/task_performing_rolling_upgrade_on_a_single_host_or_multiple_hosts.html 
sidebar: sidebar 
keywords: perform, rolling, upgrade, single, multiple, snapmanager, host, command-line, interface, cli, version 
summary: 'È possibile eseguire l"aggiornamento in sequenza su uno o più host server SnapManager utilizzando l"interfaccia a riga di comando (CLI). L"host del server SnapManager aggiornato viene quindi gestito solo con la versione successiva di SnapManager.' 
---
= Esecuzione di un aggiornamento in sequenza su uno o più host
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile eseguire l'aggiornamento in sequenza su uno o più host server SnapManager utilizzando l'interfaccia a riga di comando (CLI). L'host del server SnapManager aggiornato viene quindi gestito solo con la versione successiva di SnapManager.

Assicurarsi che tutti i prerequisiti per l'esecuzione dell'aggiornamento in sequenza siano stati completati.

. Per eseguire un aggiornamento rolling su un singolo host, immettere il seguente comando: Smorepository rollingupgrade-repository-dbnamerepo_service_name-hostrepo_host-login-usernamerepo_username-portrepo_port-upgradehosthost_with_target_database-force [-quiet | -verbose]
+
Il seguente comando esegue l'aggiornamento in sequenza di tutti i database di destinazione montati su Hosta e di un database di repository denominato repoA situato su repo_host:

+
[listing]
----

smo repository rollingupgrade
    -repository
      -dbname repoA
      -host repo_host
      -login
       -username repouser
       -port 1521
     -upgradehost hostA
----
. Per eseguire un rolling upgrade su più host, immettere il seguente comando: Smorepository rollingupgrade-repository-dbnamerepo_service_name-hostrepo_host-login-username-portrepo_port-upgradehosthost_with_target_database1,host_with_target_database2-force [-quiet | -verbose]
+

NOTE: Per più host, immettere i nomi host separati da una virgola e assicurarsi di non inserire spazio tra la virgola e il nome host successivo.inoltre, assicurarsi di inserire tutti i nomi host tra virgolette doppie.

+
Il seguente comando esegue l'aggiornamento in sequenza di tutti i database di destinazione montati sugli host, Hosta e hostB e un database di repository denominato repoA situato su repo_host:

+
[listing]
----

smo repository rollingupgrade
    -repository
      -dbname repoA
      -host repo_host
      -login
       -username repouser
       -port 1521
     -upgradehost hostA,hostB
----
. Per eseguire un aggiornamento rolling su tutti gli host di un database di repository, immettere il seguente comando: Smorepository rollingupgrade-repository-dbnamerepo_service_name-hostrepo_host-login-username_username-portrepo_port-allhosts-force [-quiet | -verbose]
+
Dopo aver aggiornato correttamente il database del repository, è possibile eseguire tutte le operazioni SnapManager sul database di destinazione.

+
L'aggiornamento di SnapManager per Oracle conserva le credenziali utente basate su host, le credenziali utente del software Oracle e le credenziali utente di Oracle Recovery Manager (RMAN) della versione precedente di SnapManager per Oracle.

+
Il seguente comando esegue l'aggiornamento in sequenza di tutti i database di destinazione disponibili in un database repository denominato repoA situato su repo_host:

+
[listing]
----

smo repository rollingupgrade
    -repository
      -dbname repoA
      -host repo_host
      -login
       -username repouser
       -port 1521
      -allhosts
----
+
** Se il server SnapManager si avvia automaticamente, è necessario riavviare il server per assicurarsi di poter visualizzare le pianificazioni.
** Se si aggiorna uno dei due host correlati, è necessario aggiornare il secondo host dopo l'aggiornamento del primo.
+
Ad esempio, se è stato creato un clone dall'host A all'host B o è stato montato un backup dall'host A all'host B, gli host A e B sono correlati tra loro. Quando si aggiorna l'host A, viene visualizzato un messaggio di avviso che richiede di aggiornare l'host B subito dopo l'aggiornamento dell'host A.

+

NOTE: I messaggi di avviso vengono visualizzati anche se il clone viene cancellato o il backup viene dismontato dall'host B durante l'aggiornamento in sequenza dell'host A. Questo perché nel repository sono presenti metadati per le operazioni eseguite sull'host remoto.





*Informazioni correlate*

xref:concept_prerequisites_for_performing_rolling_upgrade.adoc[Prerequisiti per l'esecuzione dell'aggiornamento in sequenza]
