---
permalink: windows/task_cloning_a_database_to_an_alternate_host.html 
sidebar: sidebar 
keywords: clone, create, command, database, alternate, host, cloning 
summary: È possibile utilizzare il comando clone create per clonare un backup del database su un host alternativo. 
---
= Clonazione di un database in un host alternativo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare il comando clone create per clonare un backup del database su un host alternativo.

* Creare un profilo o disporre di un profilo esistente.
* Creare un backup completo o disporre di un backup del database esistente.
* Creare una specifica di cloni o disporre di una specifica di cloni esistente.
+
.. Per clonare un database in un host alternativo, immettere il seguente comando: smo clone create -backup-label backup_label_name-newsid new_sid-host target_host-label clone_label-commentocomment_text-profileprofile_name-clonespec full_path_to_clonespecfile
+
Oracle non consente di eseguire contemporaneamente due database con lo stesso SID sullo stesso host. Per questo motivo, è necessario fornire un nuovo SID per ciascun clone. Tuttavia, è possibile avere un database su un altro host con lo stesso SID.





*Informazioni correlate*

xref:task_creating_profiles.adoc[Creazione di profili]

xref:task_cloning_databases_from_backups.adoc[Clonare i database dai backup]

xref:task_creating_clone_specifications.adoc[Creazione di specifiche di cloni]

xref:reference_the_smosmsapclone_create_command.adoc[Comando di creazione del clone smo]
