---
permalink: windows/task_adding_storage_systems_to_the_snapmanager_server_host.html 
sidebar: sidebar 
keywords: storage, system, operating, clustered, data, ontap, snapmanager, autosupport, server, host 
summary: 'Per abilitare AutoSupport, è necessario aggiungere i sistemi storage che operano in Clustered Data ONTAP all"host del server SnapManager. In SnapManager 3.3 e versioni precedenti, AutoSupport era supportato solo sui sistemi storage che operavano in 7-Mode.' 
---
= Aggiunta di sistemi storage che operano in Clustered Data ONTAP all'host del server SnapManager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per abilitare AutoSupport, è necessario aggiungere i sistemi storage che operano in Clustered Data ONTAP all'host del server SnapManager. In SnapManager 3.3 e versioni precedenti, AutoSupport era supportato solo sui sistemi storage che operavano in 7-Mode.

. Aggiungere una macchina virtuale di storage amministrativa (SVM, precedentemente nota come Vserver) e una SVM che opera in Clustered Data ONTAP all'host del server SnapManager: Sdcli transport_Protocol set -f AdminVserver_name o Vserver_name -type HTTP -user admin
+
Viene visualizzato il messaggio inserire il seguente comando:.

. Immettere la password fornita durante la creazione di SVM.
+
Una volta eseguito correttamente il comando, è stato impostato il nuovo protocollo di trasporto. viene visualizzato il messaggio.


