---
permalink: windows/task_viewing_operation_details.html 
sidebar: sidebar 
keywords: view, detail, information, particular, profile, verify, success, failure, operation, determine 
summary: 'È possibile visualizzare informazioni dettagliate su un particolare profilo per verificare l"esito positivo o negativo di un"operazione. Inoltre, consente di determinare le risorse di storage in uso per una determinata operazione.' 
---
= Visualizzazione dei dettagli delle operazioni
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile visualizzare informazioni dettagliate su un particolare profilo per verificare l'esito positivo o negativo di un'operazione. Inoltre, consente di determinare le risorse di storage in uso per una determinata operazione.

È possibile visualizzare i seguenti dettagli relativi a una determinata operazione:

* ID operazione
* Tipo di operazione
* Se l'operazione è stata forzata
* Informazioni di runtime, tra cui stato, data di inizio e di fine dell'operazione
* L'host su cui è stata eseguita l'operazione, inclusi l'ID del processo e la versione di SnapManager
* Informazioni sul repository
* Risorse di storage in uso
+
.. Per visualizzare le informazioni dettagliate relative a un ID operazione specifico, immettere il seguente comando: Operazione smo show -profile profile_name [-label label | -id ID] [-quiet | -verbose]




*Informazioni correlate*

xref:reference_the_smosmsap_operation_show_command.adoc[Il comando show dell'operazione smo]
