---
permalink: windows/task_cloning_databases_from_backups.html 
sidebar: sidebar 
keywords: clone, database, backup, create, command, cloning 
summary: È possibile clonare un database da un backup utilizzando il comando clone create. 
---
= Clonare i database dai backup
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile clonare un database da un backup utilizzando il comando clone create.

Creare prima un file di specifica clone per il database. SnapManager crea il clone in base alle informazioni contenute in questo file di specifica.

È necessario assegnare al clone un nuovo SID (System Identifier) Oracle. Non è possibile eseguire contemporaneamente due database con lo stesso SID sullo stesso host. È possibile disporre di un clone su un host diverso che utilizza lo stesso SID. Per specificare un nome univoco per il clone, utilizzare -label. Se non si utilizza questa opzione, SnapManager crea un nome univoco per il clone che include il SID, la data e l'ora.

Dopo aver clonato un database, è possibile aggiornare i file tnsname.ora sui computer client con le nuove informazioni di connessione al database clonato. I file tnsnames.ora vengono utilizzati per connettersi a un'istanza Oracle senza dover specificare le informazioni complete del database. SnapManager non aggiorna i file tnsnames.ora.

Se si utilizza il profilo creato con -include-with-online-backups, SnapManager crea sempre un backup che include i file di log dell'archivio. SnapManager consente di clonare solo i backup completi del database.

SnapManager (3.2 o versione successiva) consente di clonare i backup contenenti i file di dati e i file di log dell'archivio.

Se il log di archiviazione è disponibile da una posizione esterna, è possibile specificare la posizione esterna durante la clonazione per il ripristino del database clonato in uno stato coerente. L'utente deve assicurarsi che la posizione esterna sia accessibile da Oracle. La clonazione dei backup solo log dell'archivio non è supportata.

Sebbene il backup del registro di archiviazione venga creato insieme al backup parziale online, non è possibile creare un clone del database utilizzando questo backup.

Quando si specificano le posizioni del registro di archiviazione esterno per il ripristino del database clonato in uno stato coerente, è necessario assicurarsi di includere i nomi delle posizioni esterne in maiuscolo. Nel file system, i nomi di tutte le cartelle e sottocartelle devono essere in maiuscolo perché il database Oracle converte il percorso di destinazione in maiuscolo e prevede che i percorsi di destinazione esterni, i nomi delle cartelle e i nomi delle sottocartelle siano in maiuscolo. Se si specificano i percorsi di destinazione del log di archiviazione esterno in minuscolo, il database potrebbe non essere in grado di identificare il percorso specificato e non riuscire a ripristinare il database clonato.

È possibile clonare il backup del database dalla posizione del file di log dell'archivio esterno solo per un database standalone.

È possibile specificare l'opzione -dump come parametro facoltativo per raccogliere i file dump dopo l'operazione di creazione del clone riuscita o non riuscita.

*Clonazione del backup dei file di dati senza backup del log di archiviazione*

Quando il backup dei file di dati non include il backup del registro di archiviazione, SnapManager per Oracle clona il database in base al numero di modifica del sistema registrato durante il backup. Se non è possibile ripristinare il database clonato, viene visualizzato il messaggio di errore file di log archiviato per thread <number> e change <SCN> required to complete recovery error (Modifica richiesta per il ripristino completo), anche se SnapManager per Oracle continua a clonare il database e infine riesce a creare il clone.

Quando si esegue il cloning utilizzando il backup dei file di dati senza includere il backup del registro di archiviazione, SnapManager ripristina il database clonato fino all'ultimo SCN del registro di archiviazione, registrato durante il backup.

. Creare un file di specifica clone.
. Per creare un clone, immettere il seguente comando: Clone smo create -backup-labelbackup_name-newsidnew_sid-labelclone_label-profileprofile_name-clonespecfull_path_to_clonespecfile [-taskspeckspec] [-recover-from-location] path 1 [,<path2>...][-dump]


*Informazioni correlate*

xref:task_cloning_databases_in_the_current_state.adoc[Clonazione dei database nello stato corrente]

xref:concept_considerations_for_cloning_a_database_to_an_alternate_host.adoc[Considerazioni per clonare un database su un host alternativo]

xref:task_creating_clone_specifications.adoc[Creazione di specifiche di cloni]

xref:reference_the_smosmsapclone_create_command.adoc[Comando di creazione del clone smo]

xref:task_creating_pretask_post_task_and_policy_scripts.adoc[Creazione di script di pre-task, post-task e policy]

xref:concept_variables_available_in_the_task_scripts_for_clone_operation.adoc[Variabili disponibili negli script di attività per l'operazione di cloni]

xref:task_creating_task_scripts.adoc[Creazione di script di attività]

xref:task_storing_the_task_scripts.adoc[Memorizzazione degli script delle operazioni]
