---
permalink: windows/task_issuing_commands_from_an_alternate_host.html 
sidebar: sidebar 
keywords: issue, cli, command, host, database, snapmanager, route, appropriate, issuing, alternate 
summary: 'È possibile eseguire comandi CLI da un host diverso dall"host del database e SnapManager instraderà i comandi immessi all"host appropriato.' 
---
= Invio di comandi da un host alternativo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile eseguire comandi CLI da un host diverso dall'host del database e SnapManager instraderà i comandi immessi all'host appropriato.

Affinché il sistema invii un'operazione all'host corretto, deve prima sapere dove trovare il profilo per l'operazione. In questa procedura, il sistema mantiene il profilo per il repository delle informazioni di mappatura di un file nella home directory dell'utente sull'host locale.

. Per far sì che la home directory dell'utente locale sia consapevole delle mappature profilo-repository in modo da poter instradare la richiesta di operazione, immettere il seguente comando: smo profile Sync -repository-dbname repo_dbname-host repo_host-port repo_port-login-username repo_username [-quiet | -verbose]

