---
permalink: windows/task_adding_new_profile_to_summary_notification.html 
sidebar: sidebar 
keywords: configure, summary, email, notification, database, profile 
summary: Dopo aver configurato una notifica e-mail di riepilogo per il database del repository, è possibile aggiungere un nuovo profilo alla notifica di riepilogo utilizzando il comando di notifica di riepilogo. 
---
= Aggiunta di un nuovo profilo alle notifiche email di riepilogo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dopo aver configurato una notifica e-mail di riepilogo per il database del repository, è possibile aggiungere un nuovo profilo alla notifica di riepilogo utilizzando il comando di notifica di riepilogo.

. Immettere il seguente comando: smo profile create -profileprofile_name [-profile-passwordprofile_password] -repository-dbnamerepo_service_name-hostrepo_host-portrepo_port-login-username-username_username_dbnamedb_hostdb_host [-sidddb_name] [-{-{-nomescort]] [-nomescrivo] [-nomescrivo] [-nomescrivo-} }]] [-nomescrescrescrescrescrescrescrescrescrescrescrescrescrescrescrescrescrescrescrescrescrescrescrescrescrescrescrescrescrescrescrescrescrescrescrescrescrescrescrescrescrescrescrescrescrescrescrescrescrescrescrescrescrescrescrescrescrescrescrescrescrescrescrescr
+
Le altre opzioni per questo comando sono le seguenti:

+
[-force] (forza)


