---
permalink: windows/task_viewing_a_list_of_operations.html 
sidebar: sidebar 
keywords: view, summary, list, operation, perform, profile 
summary: È possibile visualizzare un elenco riepilogativo di tutte le operazioni eseguite rispetto a un profilo. 
---
= Visualizzazione di un elenco di operazioni
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile visualizzare un elenco riepilogativo di tutte le operazioni eseguite rispetto a un profilo.

Quando si elencano le operazioni associate a un particolare profilo, è possibile visualizzare le seguenti informazioni:

* Data di inizio e fine dell'operazione
* Stato del funzionamento
* ID operazione
* Tipo di operazione
* Host su cui è stato eseguito
+
.. Per elencare le informazioni di riepilogo di tutte le operazioni, utilizzare il seguente comando: smo Operation list profile -profile profile_name-delimiter character [-quiet | -verbose]
+
Quando viene specificata l'opzione -delimitatore, il comando elenca ogni riga su una riga separata e gli attributi in tale riga sono separati dal carattere specificato.





*Informazioni correlate*

xref:reference_the_smosmsapoperation_list_command.adoc[Il comando smo Operation list]
