---
permalink: windows/task_starting_the_snapmanager_graphical_user_interface.html 
sidebar: sidebar 
keywords: snapmanager, install, host, graphical, user, interface, gui, program, start 
summary: 'Se SnapManager è installato sull"host, avviare l"interfaccia grafica utente (GUI) per SnapManager selezionando il programma da un elenco di programmi.' 
---
= Avvio dell'interfaccia grafica di SnapManager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se SnapManager è installato sull'host, avviare l'interfaccia grafica utente (GUI) per SnapManager selezionando il programma da un elenco di programmi.

* Assicurarsi che il server SnapManager sia avviato.


È possibile avviare l'interfaccia grafica di SnapManager in uno dei seguenti modi:

* Nell'host SnapManager, fare clic su *Start* > *tutti i programmi* > *NetApp* > *SnapManager per Oracle* > *Avvia GUI SMO*.
* Se SnapManager non è installato sull'host, utilizzare Java Web Start, che scarica i componenti SnapManager e avvia la GUI.


*Informazioni correlate*

xref:task_downloading_and_starting_the_graphical_user_interface_using_java_web_start_windows.adoc[Scaricare e avviare l'interfaccia grafica utente utilizzando Java Web Start]
