---
permalink: windows/task_configuring_e_mail_notification_for_an_existing_profile.html 
sidebar: sidebar 
keywords: updating, profile, configure, receive, email, notification, completion, database, operation, configuring, existing 
summary: 'Quando si aggiorna un profilo, è possibile configurare per ricevere una notifica via email al completamento dell"operazione del database.' 
---
= Configurazione della notifica e-mail per un profilo esistente
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando si aggiorna un profilo, è possibile configurare per ricevere una notifica via email al completamento dell'operazione del database.

* È necessario configurare l'indirizzo e-mail da cui vengono inviati gli avvisi.
* È necessario inserire un singolo indirizzo e-mail o più indirizzi e-mail a cui verranno inviati gli avvisi.
+
È possibile utilizzare un elenco separato da virgole per più indirizzi. Assicurarsi che non vi sia spazio tra la virgola e l'indirizzo e-mail successivo. In alternativa, è possibile aggiungere un oggetto all'e-mail.

+

NOTE: Assicurarsi di inserire il set di indirizzi e-mail multipli tra virgolette doppie.

+
.. Immettere il seguente comando:smo profile update -profileprofile [-profile-passwordprofile_password][-database-dbnamedb_dbname-host db_host [-siddb_sid] [-login -usernamedb_username-password_db-port db_port] [{-rman_controlfile | {-sublogin -nomeaddressman] [-nomeemail [-nomeemail] [-nomeutente] [-nomeutente] [-timesemaemail][-nomeemail][-nomeemail][-nomeemail [-nomeemail][-nomeemail][-nomeemail] [-{}}}][-nomeemail][-nomeemail][-nomeemail][-nomeemail][-nomeemail][_email][-nomeemail] [-nomeemail][_email][_email][_email][_email][_email][_email][_email][_email][-nomeemail]
+
È possibile utilizzare l'opzione Success per ricevere una notifica solo per le operazioni di database riuscite e l'opzione failure per ricevere una notifica solo per le operazioni di database non riuscite.




