---
permalink: windows/task_configuring_e_mail_notification_for_a_new_profile.html 
sidebar: sidebar 
keywords: creating, new, profile, configure, email, notification, completion, database, operation, configuring 
summary: 'Quando si crea un nuovo profilo, è possibile configurare per ricevere una notifica via email al completamento dell"operazione del database.' 
---
= Configurazione della notifica e-mail per un nuovo profilo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando si crea un nuovo profilo, è possibile configurare per ricevere una notifica via email al completamento dell'operazione del database.

* È necessario configurare l'indirizzo e-mail da cui vengono inviati gli avvisi.
* È necessario utilizzare un elenco separato da virgole per più indirizzi e-mail.
+
Assicurarsi che non vi sia spazio tra la virgola e l'indirizzo e-mail successivo.

+

NOTE: Assicurarsi di inserire il set di indirizzi e-mail tra virgolette doppie.

+
.. Immettere il seguente comando: profilo smo create -profileprofile [-profile-passwordprofile_password] -repository-dbnamerepo_service_name-hostrepo_host-portrepo_port-login-username-username_username_username_nome_utente [-siddddb_nome_utente] [-{-nomesemutal] [-nomeserver] [-{] [-nomesemaconto]_nome_email [-} }] [-nome_nome_nome_utente] [-] [-nomesemaconto] [-]_nome_utente]_nome_utente] [-nomesemaconto] [-]_nome_utente] [-nomeself] [-nomeself] [-nomeself] [-nomeself] [-nomeself] [-nomeself] [-nomeself]_nome_nome_nome_nome_nome_email] [-] [-] [-nomeself]_nome_nome_
+
Le altre opzioni per questo comando sono le seguenti:

+
[-force] (forza)

+

NOTE: SnapManager supporta fino a 1000 caratteri per gli indirizzi e-mail.

+
Quando si crea un backup dei file di dati e dei file di log di archiviazione insieme utilizzando il profilo (per la creazione di backup del log di archiviazione separati) e la creazione del backup del file di dati non riesce, viene inviata una notifica e-mail con il backup dei dati come nome dell'operazione invece del backup dei dati e del backup dei log di archiviazione. Una volta eseguita correttamente l'operazione di backup del file di dati e del file di log dell'archivio, viene visualizzato il seguente output:

+
[listing]
----

Profile Name    : PROF_31
Operation Name 	: Data Backup and Archive Logs Backup
Database SID   	: TENDB1
Database Host 	 : repo1.rtp.org.com
Start Date 	    : Fri Sep 23 13:37:21 EDT 2011
End Date 	      : Fri Sep 23 13:45:24 EDT 2011
Status 	        : SUCCESS
Error messages 	:
----



