---
permalink: windows/task_order_of_performing_operations.html 
sidebar: sidebar 
keywords: snapmanager, enable, perform, operation, backup, cloning, clone, operation, order, perform 
summary: 'SnapManager consente di eseguire diverse operazioni, ad esempio la creazione di profili, l"esecuzione di backup e la clonazione dei backup. Queste operazioni devono essere eseguite in un ordine specifico.' 
---
= Ordine di esecuzione delle operazioni
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager consente di eseguire diverse operazioni, ad esempio la creazione di profili, l'esecuzione di backup e la clonazione dei backup. Queste operazioni devono essere eseguite in un ordine specifico.

. Creare un profilo in un repository esistente utilizzando il comando di creazione del profilo smo.
+

NOTE: L'utente Oracle specificato per il database di destinazione deve disporre dei privilegi sysdba.

+
Nell'esempio seguente viene illustrato il comando per creare un profilo:

+
[listing]
----
smo profile create -profile prof1 -profile-password prof1cred
-repository -dbname HR1 -login -username admin -host server1 -port 1521
-database -dbname dedb -login -username db_oper2
-password dbpw1 -host server1 -port 1521
----
. Creare un backup su un profilo esistente utilizzando il comando smo backup create.
+
Nell'esempio seguente viene illustrato il comando per creare un backup:

+
[listing]
----
smo backup create -profile prof1 -full -offline -label full_backup_prof1 -force
----
. Ripristinare e ripristinare un backup del database sullo storage primario utilizzando il comando di ripristino del backup smo.
+
L'esempio seguente mostra il comando per ripristinare un backup:

+
[listing]
----
smo backup restore -profile prof1 -label full_backup_prof1
-complete -recover -alllogs
----
. Creare una specifica di clone utilizzando il comando modello clone smo.
+
È possibile utilizzare la procedura guidata Clone nell'interfaccia grafica utente (GUI) per creare una specifica di cloni del modello. È anche possibile creare il file di specifica del clone utilizzando un editor di testo.

. Clonare un database con un backup esistente utilizzando il comando di creazione del clone smo.
+
Per specificare le specifiche di storage e database per il clone, è necessario disporre di una specifica per il clone o crearne una.

+
Nell'esempio seguente viene illustrato il comando per creare un clone:

+
[listing]
----
smo clone create -profile prof1 -backup-label full_backup_prof1
-newsid clone1 -label prof1_clone -clonespec C:\\clone_spec\\prof1_clonespec.xml
----

