---
permalink: windows/task_removing_history_configuration_associated_with_a_single_profile_or_multiple_profiles.html 
sidebar: sidebar 
keywords: snapmanager, enable, remove, history, setting, operation, information, removing, single, multiple, profile 
summary: 'SnapManager consente di rimuovere le impostazioni della cronologia di un"operazione SnapManager. Questa operazione rimuove tutte le informazioni della cronologia associate a un singolo profilo o a pi첫 profili.' 
---
= Rimozione delle impostazioni della cronologia associate a uno o pi첫 profili
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager consente di rimuovere le impostazioni della cronologia di un'operazione SnapManager. Questa operazione rimuove tutte le informazioni della cronologia associate a un singolo profilo o a pi첫 profili.

. Per rimuovere la cronologia delle operazioni SnapManager associate a un singolo profilo o a pi첫 profili, immettere il seguente comando: smo history remove -profile {-name, profile_name [profile_name1, profile_name2] | all-repository-login [-passwordrepo_password] -usernamerepo_nome_dbnamerepo_dbname-ostreppo_operazione -nomeporta_} {} operazione_disquiet_nome_operazione -nome1_operazione -nomeporta_operazione_operazioni_operazioni_operazioni_operazioni_operazioni_operazioni_di_operazioni_operazioni_di_operazioni_di_operazioni_di_di_operazioni_

