---
permalink: unix-administration/concept_general_layout_and_configuration.html 
sidebar: sidebar 
keywords: recommend, general, database, layout, storage, configuration, avoid, issue, disk, group, file, lun 
summary: Conoscere i layout generali dei database e le configurazioni di storage consigliati può aiutare a evitare problemi relativi a gruppi di dischi, tipi di file e spazi delle tabelle. 
---
= Layout generali del database e configurazioni di storage consigliati
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Conoscere i layout generali dei database e le configurazioni di storage consigliati può aiutare a evitare problemi relativi a gruppi di dischi, tipi di file e spazi delle tabelle.

* Non includere nel database file di più tipi DI file system SAN o di gestore di volumi.
+
Tutti i file che costituiscono un database devono risiedere nello stesso tipo di file system.

* SnapManager richiede un multiplo di blocchi di dimensioni 4K.
* Includere l'identificatore del sistema di database nel file oratab.
+
Includere una voce nel file oratab per ciascun database da gestire. SnapManager si affida al file oratab per determinare quale sede Oracle utilizzare.

* Se si desidera registrare i backup di SnapManager con Oracle Recovery Manager (RMAN), è necessario creare profili abilitati per RMAN.


Se si desidera sfruttare il nuovo ripristino basato su volume o il ripristino completo del gruppo di dischi, prendere in considerazione le seguenti linee guida relative ai file system e ai gruppi di dischi:

* Più database non possono condividere lo stesso gruppo di dischi ASM (Automatic Storage Management).
* Un gruppo di dischi contenente file di dati non può contenere altri tipi di file.
* Il numero di unità logica (LUN) per il gruppo di dischi del file di dati deve essere l'unico oggetto nel volume di storage.


Di seguito sono riportate alcune linee guida per la separazione dei volumi:

* I file di dati di un solo database devono essere presenti nel volume.
* È necessario utilizzare volumi separati per ciascuna delle seguenti classificazioni di file: File binari di database, file di dati, file di log di ripristino online, file di log di ripristino archiviati e file di controllo.
* Non è necessario creare un volume separato per i file di database temporanei perché SnapManager non esegue il backup dei file di database temporanei.

