---
permalink: unix-administration/concept_how_to_collect_dump_files.html 
sidebar: sidebar 
keywords: -dump, snapmanager, command, collect, dump, file, successful, fail, creating, updating, verify 
summary: 'È possibile includere -dump nel comando SnapManager per raccogliere i file dump dopo un"operazione SnapManager riuscita o non riuscita.' 
---
= Come raccogliere i file dump
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile includere -dump nel comando SnapManager per raccogliere i file dump dopo un'operazione SnapManager riuscita o non riuscita.

È possibile raccogliere i file dump per le seguenti operazioni SnapManager:

* Creazione di profili
* Aggiornamento dei profili
* Creazione di backup
* Verifica dei backup
* Eliminazione dei backup
* Liberare i backup
* Montaggio dei backup
* Smontare i backup
* Ripristino dei backup
* Creazione di cloni
* Eliminazione dei cloni
* Suddivisione dei cloni



NOTE: Quando si crea un profilo, è possibile raccogliere i file dump solo se l'operazione ha esito positivo. Se si verifica un errore durante la creazione di un profilo, è necessario utilizzare il comando smosystem dump. Per i profili di successo, è possibile utilizzare i comandi dump di smooperation e dump di smoprofile per raccogliere i file dump.

*Esempio*

[listing]
----

      smo  backup create -profile targetdb1_prof1 -auto -full -online -dump
----