---
permalink: unix-administration/concept_limitations_related_to_oracle_database.html 
sidebar: sidebar 
keywords: snapmanager, limitations, oracle, database, 10gr2, 11gr1, 11gr2, 12_c_, ocds, dnfs 
summary: Prima di iniziare a lavorare con SnapManager, è necessario conoscere le limitazioni relative a Oracle Database. 
---
= Limitazioni relative al database Oracle
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di iniziare a lavorare con SnapManager, è necessario conoscere le limitazioni relative a Oracle Database.

Le limitazioni sono le seguenti:

* SnapManager supporta le versioni di Oracle 10gR2, 11gR1, 11gR2 e 12__c__, ma non supporta Oracle 10gR1 come repository o database di destinazione.
* SnapManager non supporta l'utilizzo di un indirizzo IP DI SCANSIONE al posto di un nome host.
+
SCAN IP è una nuova funzionalità di Oracle 11gR2.

* SnapManager non supporta Oracle Cluster file System (OCFS).
* Oracle 11g in un ambiente Direct NFS (DNFS) consente configurazioni aggiuntive del punto di montaggio nel file oranfstab, ad esempio percorsi multipli per il bilanciamento del carico.
+
SnapManager non modifica il file oranfstab. È necessario aggiungere manualmente le proprietà aggiuntive che si desidera utilizzare nel database clonato, nel file oranfstab.

* Il supporto per Oracle Database 9i è obsoleto da SnapManager 3.2.
* Il supporto per Oracle Database 10gR2 (versioni precedenti alla 10.2.0.5) è obsoleto rispetto a SnapManager 3.3.1.



NOTE: Identificare le diverse versioni dei database Oracle supportate facendo riferimento alla matrice di interoperabilità.

*Informazioni correlate*

http://support.netapp.com/NOW/products/interoperability/["Matrice di interoperabilità: support.netapp.com/NOW/products/interoperability"]
