---
permalink: unix-administration/concept_what_cloning_is.html 
sidebar: sidebar 
keywords: clone, database, replica, original, database, clone, full, backup, current, system, dlexclone, snapmanager 
summary: È possibile clonare un database per creare una replica esatta del database originale. È possibile creare il clone da un backup completo o dallo stato corrente del database. 
---
= Cos'è Cloning
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile clonare un database per creare una replica esatta del database originale. È possibile creare il clone da un backup completo o dallo stato corrente del database.

Di seguito sono riportati alcuni dei vantaggi della creazione di un clone mediante SnapManager:

|===
| Vantaggi | Dettagli 


 a| 
Velocità
 a| 
L'operazione di clonazione SnapManager utilizza la funzione FlexClone disponibile con Data ONTAP. Ciò consente di clonare rapidamente grandi volumi di dati.



 a| 
Efficienza dello spazio
 a| 
Quando si crea un clone utilizzando SnapManager, lo spazio è necessario solo per le modifiche tra il backup e il clone. Un clone di SnapManager è una copia Snapshot scrivibile del database originale e può crescere in base alle esigenze. Al contrario, un clone fisico del database richiede uno spazio sufficiente per copiare l'intero database.



 a| 
Copia virtuale
 a| 
È possibile utilizzare il database clonato come se fosse il database originale. Ad esempio, è possibile utilizzare un clone per test, verifiche di piattaforme e aggiornamenti, simulazioni multiple su un set di dati di grandi dimensioni e test e staging della sede remota. Le modifiche apportate al clone non influiscono sul database originale. Una volta clonato il database, il database clonato è completamente operativo.



 a| 
Semplicità
 a| 
È possibile clonare un database su qualsiasi host utilizzando i comandi SnapManager.

|===
È possibile clonare un backup sullo storage primario (locale) o su un backup protetto sullo storage secondario (remoto). Tuttavia, non è possibile clonare un backup se l'operazione di backup è in corso o se il backup è stato trasferito allo storage secondario.

Prima di clonare un database, è necessario assicurarsi che siano soddisfatti i seguenti prerequisiti:

* Assicurarsi che la directory [/etc|/var/opt/oracle]/oratab non contenga una voce che punta all'identificatore del sistema di destinazione.
* Eliminare il file <SID>.ora spfilserie da €ORACLE_HOME/dbs.
* Eliminare il file init <SID>.ora da €ORACLE_HOME/dbs.
* Eliminare le destinazioni di dump Oracle specificate nel file di specifica del clone.
* Eliminare i file di controllo Oracle specificati nel file di specifica del clone.
* Eliminare i file di log di ripristino Oracle specificati nel file di specifica del clone.


È necessario assegnare al clone un nuovo identificatore di sistema. Non è possibile eseguire contemporaneamente due database con lo stesso identificatore di sistema sullo stesso host. È possibile avere un clone su un host diverso utilizzando lo stesso identificatore di sistema. È possibile assegnare un'etichetta al clone o lasciare che SnapManager crei un'etichetta utilizzando l'identificatore di sistema, la data e l'ora di creazione del clone.

Quando si inserisce un'etichetta, non includere spazi o caratteri speciali.

Nell'ambito del processo di cloning, SnapManager crea i file e i parametri Oracle necessari per il database clonato. Un esempio di un file Oracle necessario è inatit <SID>.ora.

Quando si clona un database, SnapManager crea un nuovo file init <SID>.ora per il database nella directory €ORACLE_HOME/dbs.

Quando SnapManager clona lo storage per un database, crea anche un nuovo punto di montaggio del file system, ma non modifica la struttura della directory sotto il punto di montaggio dall'interfaccia CLI di SnapManager. Tuttavia, dalla GUI di SnapManager, è possibile modificare la struttura della directory e i metadati del file system.

Oracle 11g in un ambiente Direct NFS (DNFS) consente una configurazione aggiuntiva dei punti di montaggio, ad esempio percorsi multipli per il bilanciamento del carico nel file oranfstab. SnapManager non modifica questo file, pertanto tutte le proprietà aggiuntive che si desidera utilizzare per un clone devono essere aggiunte manualmente al file oranfstab dopo la clonazione con SnapManager.

È possibile clonare un database RAC (Real Application Cluster) e un database non in cluster. Un clone RAC viene avviato come singolo database.

È possibile clonare un backup del database sull'host in cui risiede il database o su un host alternativo.

È inoltre possibile clonare un database ASM su un host remoto. Durante questa operazione, è necessario assicurarsi che l'istanza di ASM sia in esecuzione sull'host remoto.

Se il database clonato utilizzava una spfile, SnapManager crea una spfile per il clone. Il file viene inserito nella directory Oracle_HOME/dbs e viene creata la struttura di directory per i file di diagnostica. Il nome del file è spfile <SID>.ora.
