---
permalink: unix-administration/reference_the_smosmsapclone_show_command.html 
sidebar: sidebar 
keywords: run, clone, show, command, display, information, database, clone, specified, profile, smo 
summary: È possibile eseguire il comando clone show per visualizzare le informazioni sui cloni del database per il profilo specificato. 
---
= Comando di visualizzazione del clone smo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile eseguire il comando clone show per visualizzare le informazioni sui cloni del database per il profilo specificato.



== Sintassi

[listing]
----

        smo clone show
-profile profile_name
\[-id  guid \| -label clone_name\]
\[-quiet \| -verbose\]
----


== Parametri

* *-profile_name*
+
Specifica l'elenco dei cloni associati al profilo. Il profilo contiene l'identificatore del database e altre informazioni del database.

* *-id guid*
+
Mostra le informazioni sul clone con il GUID specificato. Il GUID viene generato da SnapManager quando si crea un clone. È possibile utilizzare il comando smo clone show per visualizzare il GUID per ciascun clone.

* *-label label nome_etichetta*
+
Mostra le informazioni sul clone con l'etichetta specificata.

* *-quiet*
+
Visualizza solo i messaggi di errore nella console. L'impostazione predefinita prevede la visualizzazione dei messaggi di errore e di avviso.

* *-dettagliato*
+
Visualizza messaggi di errore, di avviso e informativi nella console.





== Esempio

Nell'esempio seguente vengono visualizzate informazioni sul clone:

[listing]
----
smo clone show -profile SALES1 -label full_backup_sales_May -verbose
----
Il seguente output mostra informazioni su un clone di un backup sullo storage primario:

[listing]
----
Clone id: 8abc013111b916e30111b916ffb40001
Clone status: SUCCESS
Clone SID: hsdbc
Clone label: hsdbc
Clone comment: null
Clone start time: 2007-04-03 16:15:50
Clone end time: 2007-04-03 16:18:17
Clone host: Host1
Filesystem: /mnt/ssys1/data_clone
File: /mnt/ssys1/data_clone/hsdb/sysaux01.dbf
File: /mnt/ssys1/data_clone/hsdb/undotbs01.dbf
File: /mnt/ssys1/data_clone/hsdb/users01.dbf
File: /mnt/ssys1/data_clone/hsdb/system01.dbf
File: /mnt/ssys1/data_clone/hsdb/undotbs02.dbf
Backup id: 8abc013111a450480111a45066210001
Backup label: full_backup_sales_May
Backup SID: hsdb1
Backup comment:
Backup start time: 2007-03-30 15:26:30
Backup end time: 2007-03-30 15:34:13
Backup host: server1
----
Il seguente output mostra informazioni su un clone di un backup protetto su uno storage secondario:

[listing]
----
clone show -label clone_CLSTEST -profile
TEST_USER_NFSTEST_DIRMAC
Clone id:8abc01ec16514aec0116514af52f0001
Clone status: SUCCESS
Clone SID: CLSTEST
Clone label: clone_CLSTEST
Clone comment:comment_for_clone_CLSTEST
Clone start time: 2007-11-18 00:46:10
Clone end time: 2007-11-18 00:47:54
Clone host: dirmac
Filesystem: /ant/fish/bt_dirmac_nfs_clone
File: /ant/fish/bt_dirmac_nfs_clone/datafiles/sysaux01.dbf
File: /ant/fish/bt_dirmac_nfs_clone/datafiles/system01.dbf
File: /ant/fish/bt_dirmac_nfs_clone/datafiles/undotbs01.dbf
File: /ant/fish/bt_dirmac_nfs_clone/datafiles/users01.dbf
Backup id: 8abc01ec16514883011651488b580001
Backup label:full_backup
Backup SID: NFSTEST
Backup comment:
Backup start time: 2007-11-18 00:43:32
Backup end time: 2007-11-18 00:45:30
Backup host: dirmac
Storage System: fish (Secondary storage)
Volume: bt_dirmac_nfs
Snapshot:smo_user_nfstest_b_nfstest_f_c_1_8abc01ec16511d6a0116511d73590001_0
File: /ant/fish/bt_dirmac_nfs/archlogs/1_14_638851420.dbf
File: /ant/fish/bt_dirmac_nfs/datafiles/sysaux01.dbf
File: /ant/fish/bt_dirmac_nfs/datafiles/undotbs01.dbf
File: /ant/fish/bt_dirmac_nfs/archlogs/1_13_638851420.dbf
File: /ant/fish/bt_dirmac_nfs/archlogs_2/1_16_638851420.dbf
File: /ant/fish/bt_dirmac_nfs/datafiles/users01.dbf
File: /ant/fish/bt_dirmac_nfs/controlfiles/SMBakCtl_1195361899651_2
File: /ant/fish/bt_dirmac_nfs/datafiles/system01.dbf
----
*Informazioni correlate*

xref:task_viewing_detailed_clone_information.adoc[Visualizzazione di informazioni dettagliate sui cloni]
