---
permalink: unix-administration/reference_the_smosmsapbackup_unmount_command.html 
sidebar: sidebar 
keywords: run, backup, unmount, command, smo 
summary: È possibile eseguire il comando di disinstallazione del backup per smontare un backup. 
---
= Il comando smo backup unmount
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile eseguire il comando di disinstallazione del backup per smontare un backup.



== Sintassi

[listing]
----

        smo backup unmount
-profile profile_name
[-label label \[-data \| -archivelogs\] \| \[-id id\]
\[-force\]
\[-dump\]
\[-quiet \| -verbose\]
----


== Parametri

* *-profile_name*
+
Specifica il profilo per il quale si desidera smontare un backup. Il profilo contiene l'identificatore del database e altre informazioni del database.

* id *-id*
+
Disinstalla il backup con il GUID specificato. Il GUID viene generato da SnapManager quando si crea un backup. È possibile utilizzare il comando smo backup list per visualizzare il GUID per ciascun backup.

* etichetta **
+
Disinstalla il backup con l'etichetta specificata.

* *-dati*
+
Specifica i file di dati.

* *-archivelogs*
+
Specifica i file di log dell'archivio.

* *-dump*
+
Raccoglie i file dump dopo un'operazione di disinstallazione riuscita o non riuscita.

* *-force*
+
Consente di rimuovere il backup anche in caso di problemi di liberare le risorse associate al backup. SnapManager tenta di smontare il backup e di ripulire le risorse associate. Il log mostra che l'operazione di disinstallazione ha avuto esito positivo, ma potrebbe essere necessario ripulire manualmente le risorse in caso di errori nel log.

* *-quiet*
+
Visualizza solo i messaggi di errore nella console. L'impostazione predefinita prevede la visualizzazione dei messaggi di errore e di avviso.

* *-dettagliato*
+
Visualizza messaggi di errore, di avviso e informativi nella console.





== Esempio

Di seguito viene riportato un esempio di operazione di disinstallazione:

[listing]
----
# smo backup unmount -label test -profile SALES1 -verbose
----
[listing]
----
SMO-13046 [INFO ]: Operation GUID 8abc013111b909eb0111b90a02f50001 starting on Profile SALES1
SMO-08028 [INFO ]: Beginning to disconnect connected mount(s)
[/u/user1/mnt/_mnt_ssys1_logs_SMO_SALES1_hsdb1_F_C_1_8abc013111a450480111a45066210001,
 /u/user1/mnt/_mnt_ssys1_data_SMO_SALES1_hsdb1_F_C_1_8abc013111a450480111a45066210001].
SMO-08030 [INFO ]: Done disconnecting connected mount(s)
[/u/user1/mnt/_mnt_ssys1_logs_SMO_SALES1_hsdb1_F_C_1_8abc013111a450480111a45066210001,
 /u/user1/mnt/_mnt_ssys1_data_SMO_SALES1_hsdb1_F_C_1_8abc013111a450480111a45066210001].
SMO-13037 [INFO ]: Successfully completed operation: Backup Unmount
SMO-13048 [INFO ]: Operation Status: SUCCESS
SMO-13049 [INFO ]: Elapsed Time: 0:00:33.715
Operation Id [8abc013111b909eb0111b90a02f50001] succeeded.
----
*Informazioni correlate*

xref:task_unmounting_backups.adoc[Smontare i backup]
