---
permalink: unix-administration/reference_the_smo_notification_removesummarynotification_command.html 
sidebar: sidebar 
keywords: command, disable, summary, notification, multiple, profile, database, remove 
summary: Questo comando disattiva la notifica di riepilogo per più profili in un database repository. 
---
= Il comando di notifica smo remove-summary-notification
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Questo comando disattiva la notifica di riepilogo per più profili in un database repository.



== Sintassi

[listing]
----

        smo notification remove-summary-notification
-repository
-dbname repo_service_name
-port repo_port
-host repo_host
-login -username repo_username
\[-quiet \| -verbose\]
----


== Parametri

* *-repository*
+
Le opzioni che seguono -repository specificano i dettagli del database per il repository.

* *-port repo_port*
+
Specifica il numero di porta TCP utilizzato per accedere al database in cui è memorizzato il repository.

* *-dbname repo_service_name*
+
Specifica il nome del database in cui è memorizzato il repository. Utilizzare il nome globale o il SID.

* *-host repo_host*
+
Specifica il nome o l'indirizzo IP del computer host su cui viene eseguito il database del repository.

* *-login repo_username*
+
Specifica il nome di accesso necessario per accedere al database in cui è memorizzato il repository.

* *-quiet*
+
Visualizza solo i messaggi di errore sulla console. L'impostazione predefinita prevede la visualizzazione dei messaggi di errore e di avviso.

* *-dettagliato*
+
Visualizza messaggi di errore, di avviso e informativi sulla console.



Nell'esempio seguente viene disattivata la notifica di riepilogo per più profili in un database di repository.

[listing]
----

smo notification remove-summary-notification –repository –port 1521 –dbname repo2 –host 10.72.197.133 –login -username oba5
----