---
permalink: unix-administration/reference_the_smosmsapprofile_update_command.html 
sidebar: sidebar 
keywords: run, profile, update, command, information, existing, profile, smo 
summary: È possibile eseguire il comando di aggiornamento del profilo per aggiornare le informazioni relative a un profilo esistente. 
---
= Il comando di aggiornamento del profilo smo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile eseguire il comando di aggiornamento del profilo per aggiornare le informazioni relative a un profilo esistente.



== Sintassi

[listing]
----

        smo profile update
-profile profile
\[-new-profile new_profile_name\]
\[-profile-password profile_password\]
[-database
-dbname db_dbname
-host db_host
\[-sid db_sid\]
[-login
\[-username db_username -password db_password -port db_port\]
 \[-asminstance -asmusername asminstance_username  -asmpassword asminstance_password\]]
[\{-rman  \{-controlfile \| \{\{-login
-username  rman_username
-password  rman_password \}
\[-tnsname  tnsname\]\}\}\} \|
-remove-rman\]
-osaccount osaccount
-osgroup osgroup
[-retain
\[-hourly \[-count n\] \[-duration m\]\]
\[-daily \[-count n\] \[-duration m\]]
\[-weekly \[-count n\] \[-duration m\]]
\[-monthly \[-count n\] \[-duration m\]]]]
-comment comment
-snapname-patternpattern
[-protect \[-protection-policy policy_name\] \| \[-noprotect\]]
[-summary-notification]
[-notification
\[-success
-email email_address1,email_address2
-subject subject_pattern\]
\[-failure
-email email_address1,email_address2
-subject subject_pattern]
[-separate-archivelog-backups
-retain-archivelog-backups
-hours  hours |
-days days |
-weeks weeks |
-months months
[-protect \[-protection-policy policy_name\] \| \[-noprotect\]]
[-include-with-online-backups \| -no-include-with-online-backups]]
[-dump]
\[-quiet \| -verbose\]
----


== Parametri

Se il criterio di protezione è impostato sul profilo, non è possibile modificarlo utilizzando SnapManager. È necessario modificare il criterio utilizzando la console di Protection Manager.

* *-profilo profilo*
+
Specifica il nome del profilo. Questo nome può contenere fino a 30 caratteri e deve essere univoco all'interno dell'host.

* *-profile-password profile_password*
+
Specifica la password per il profilo.

* *-new-profile new_profile_name*
+
Specifica il nuovo nome che è possibile fornire per un profilo.

* *-database*
+
Specifica i dettagli del database descritti dal profilo. Si tratta del database di cui verrà eseguito il backup, il ripristino e così via.

* *-dbname db_dbname*
+
Specifica il nome del database descritto dal profilo. È possibile utilizzare il nome globale o l'identificatore di sistema.

* *-host db_host*
+
Specifica il nome o l'indirizzo IP del computer host su cui viene eseguito il database.

* *-sid db_sid*
+
Specifica l'identificativo di sistema del database descritto dal profilo. Per impostazione predefinita, SnapManager utilizza il nome del database come identificatore di sistema. Se l'identificatore di sistema è diverso dal nome del database, è necessario specificarlo utilizzando l'opzione -sid.

+
Ad esempio, se si utilizzano i cluster di applicazioni reali Oracle, è necessario specificare l'identificativo di sistema SID dell'istanza RAC sul nodo RAC da cui viene eseguito SnapManager.

* *-login*
+
Specifica i dettagli di accesso al repository.

* *-nome utente repo_nome utente*
+
Specifica il nome utente richiesto per accedere al database del repository.

* *-port repo_port*
+
Specifica il numero di porta TCP richiesto per accedere al database del repository.

* *-database*
+
Specifica i dettagli del database descritti dal profilo. Si tratta del database di cui verrà eseguito il backup, il ripristino o il cloning.

* *-dbname db_dbname*
+
Specifica il nome del database descritto dal profilo. È possibile utilizzare il nome globale o l'identificatore di sistema.

* *-host db_host*
+
Specifica il nome o l'indirizzo IP del computer host su cui viene eseguito il database.

* *-login*
+
Specifica i dettagli di accesso al database.

* *-nome utente db_nome utente*
+
Specifica il nome utente richiesto per accedere al database descritto dal profilo.

* *-password db_password*
+
Specifica la password richiesta per accedere al database descritto dal profilo.

* *-port db_port*
+
Specifica il numero di porta TCP richiesto per accedere al database descritto dal profilo.

* *-preminenza*
+
Specifica le credenziali utilizzate per accedere all'istanza di Automatic Storage Management (ASM).

* *-asmusername asminstance_username*
+
Specifica il nome utente utilizzato per accedere all'istanza di ASM.

* *-asmpassword asminstance_password*
+
Specifica la password utilizzata per accedere all'istanza di ASM.

* *-rman*
+
Specifica i dettagli utilizzati da SnapManager per catalogare i backup con Oracle Recovery Manager (RMAN).

* *-controlfile*
+
Specifica i file di controllo del database di destinazione invece di un catalogo come repository RMAN.

* *-login*
+
Specifica i dettagli di accesso RMAN.

* *-password rman_password*
+
Specifica la password utilizzata per accedere al catalogo RMAN.

* *-username rman_username*
+
Specifica il nome utente utilizzato per accedere al catalogo RMAN.

* *-tnsname tnsname*
+
Specifica il nome di connessione tnsname (definito nel file tsname.ora).

* *-remove-rman*
+
Specifica di rimuovere RMAN sul profilo.

* *-osaccount*
+
Specifica il nome dell'account utente del database Oracle. SnapManager utilizza questo account per eseguire le operazioni Oracle, ad esempio l'avvio e lo spegnimento. In genere, è l'utente che possiede il software Oracle sull'host, ad esempio oracle.

* *-ossgroup*
+
Specifica il nome del nome del gruppo di database Oracle associato all'account oracle.

* *-retain [-hourly [-countn] [-duration m]] [-giornaliero [-count n] [-duration m]] [-settimanale [-count n][-duration m]] [-mensile [-count n][-duration m]]*
+
Specifica la classe di conservazione (oraria, giornaliera, settimanale, mensile) per un backup.

+
Per ogni classe di conservazione, è possibile specificare un conteggio di conservazione o una durata di conservazione o entrambe. La durata è espressa in unità della classe (ad esempio, ore per ora o giorni per giorno). Ad esempio, se l'utente specifica solo una durata di conservazione di 7 per i backup giornalieri, SnapManager non limiterà il numero di backup giornalieri per il profilo (poiché il numero di conservazione è 0), ma SnapManager eliminerà automaticamente i backup giornalieri creati oltre 7 giorni fa.

* *-commento commento*
+
Specifica il commento per un profilo.

* *-snapname-pattern pattern*
+
Specifica il modello di denominazione per le copie Snapshot. È inoltre possibile includere testo personalizzato, ad esempio HAOPS per operazioni altamente disponibili, in tutti i nomi delle copie Snapshot. È possibile modificare il modello di denominazione della copia Snapshot quando si crea un profilo o dopo averlo creato. Il modello aggiornato si applica solo alle copie Snapshot che non si sono ancora verificate. Le copie Snapshot esistenti conservano il modello Snapname precedente. È possibile utilizzare diverse variabili nel testo del modello.

* *-protect [-protection-policypolicy_name] | [-noprotect]*
+
Indica se il backup deve essere protetto o meno nello storage secondario.

+

NOTE: Se -Protect viene specificato senza -Protection-policy, il dataset non avrà una policy di protezione. Se viene specificato -Protect e -Protection-policy non viene impostato al momento della creazione del profilo, è possibile impostarlo successivamente tramite il comando di aggiornamento del profilo bysmo o impostarlo dall'amministratore dello storage utilizzando la console di Protection Manager .

+
L'opzione -noprotect specifica di non proteggere il profilo sullo storage secondario.

* *-summary-notification*
+
Specifica che la notifica email di riepilogo è attivata per il profilo esistente.

* *-notification [-success-email email email_address1,email address2 -subject subject_pattern]*
+
Attiva la notifica e-mail per il profilo esistente in modo che i destinatari ricevano i messaggi e-mail quando l'operazione SnapManager ha esito positivo. È necessario inserire un singolo indirizzo e-mail o più indirizzi e-mail a cui inviare gli avvisi e-mail e un modello di oggetto e-mail per il profilo esistente.

+
È possibile modificare il testo dell'oggetto durante l'aggiornamento del profilo o includere il testo dell'oggetto personalizzato. L'oggetto aggiornato si applica solo ai messaggi e-mail non inviati. È possibile utilizzare diverse variabili per l'oggetto dell'e-mail.

* *-notification [-failure -email email email_address1,email address2 -subject subject_pattern]*
+
Attiva la notifica e-mail per il profilo esistente in modo che i destinatari ricevano i messaggi e-mail quando l'operazione SnapManager non riesce. È necessario inserire un singolo indirizzo e-mail o più indirizzi e-mail a cui inviare gli avvisi e-mail e un modello di oggetto e-mail per il profilo esistente.

+
È possibile modificare il testo dell'oggetto durante l'aggiornamento del profilo o includere il testo dell'oggetto personalizzato. L'oggetto aggiornato si applica solo ai messaggi e-mail non inviati. È possibile utilizzare diverse variabili per l'oggetto dell'e-mail.

* *-storage-backup-separati*
+
Separa il backup del registro di archiviazione dal backup del file di dati. Si tratta di un parametro facoltativo che è possibile fornire durante la creazione del profilo. Dopo aver separato i backup utilizzando questa opzione, è possibile creare backup solo file di dati o backup solo log di archivio.

* *-retain-archiveog-backups -ore | -daysdays | -weeksweeks| -monthsmonths*
+
Specifica che i backup del registro di archiviazione vengono conservati in base alla durata di conservazione del registro di archiviazione (oraria, giornaliera, settimanale, mensile).

* *-protect [-protection-policypolicy_name] | -noprotect*
+
Specifica che i file di log dell'archivio sono protetti in base al criterio di protezione del log dell'archivio.

+
Specifica che i file di log dell'archivio non sono protetti utilizzando l'opzione -noprotect.

* *-include-with-online-backups | -no-include-with-online-backups*
+
Specifica che il backup del registro di archiviazione è incluso insieme al backup del database online.

+
Specifica che i backup del registro di archiviazione non sono inclusi insieme al backup del database online.

* *-dump*
+
Specifica che i file dump vengono raccolti dopo l'operazione di creazione del profilo.

* *-quiet*
+
Visualizza solo i messaggi di errore nella console. L'impostazione predefinita prevede la visualizzazione dei messaggi di errore e di avviso.

* *-dettagliato*
+
Visualizza messaggi di errore, di avviso e informativi nella console.





== Esempio

Nell'esempio seguente vengono modificate le informazioni di accesso per il database descritto dal profilo e la notifica e-mail viene configurata per questo profilo:

[listing]
----
smo profile update -profile SALES1 -database -dbname SALESDB
 -sid SALESDB -login -username admin2 -password d4jPe7bw -port 1521
-host server1 -profile-notification -success -e-mail Preston.Davis@org.com -subject success
Operation Id [8abc01ec0e78ec33010e78ec3b410001] succeeded.
----
*Informazioni correlate*

xref:task_changing_profile_passwords.adoc[Modifica delle password del profilo]

xref:concept_how_snapmanager_retains_backups_on_the_local_storage.adoc[In che modo SnapManager conserva i backup sullo storage locale]
