---
permalink: unix-administration/reference_the_smosmsapbackup_mount_command.html 
sidebar: sidebar 
keywords: run, backup, mount, command, perform, recover, operation, external, tool, smo 
summary: 'È possibile eseguire il comando di montaggio del backup per montare un backup al fine di eseguire un"operazione di ripristino utilizzando uno strumento esterno.' 
---
= Il comando di montaggio del backup smo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile eseguire il comando di montaggio del backup per montare un backup al fine di eseguire un'operazione di ripristino utilizzando uno strumento esterno.



== Sintassi

[listing]
----

        smo backup mount
-profile profile_name
[-label label \[-data \| -archivelogs\] \| \[-id id\]
[-host  host]
\[-from-secondary \{-copy-id id\}\]
\[-dump\]
[-quiet | -verbose]
----


== Parametri

* *-profile_name*
+
Specifica il profilo associato al backup che si desidera montare. Il profilo contiene l'identificatore del database e altre informazioni del database.

* *-id guid*
+
Consente di montare il backup con il GUID specificato. Il GUID viene generato da SnapManager quando si crea un backup. È possibile utilizzare il comando smo backup list per visualizzare il GUID per ciascun backup.

* etichetta **
+
Consente di montare il backup con l'etichetta specificata.

* *-dati*
+
Specifica i file di dati.

* *-archivelogs*
+
Specifica i file di log dell'archivio.

* *-from-secondary -copy-id id*
+
Consente di montare il backup dallo storage secondario. Se questa opzione non viene specificata, SnapManager installa il backup dallo storage primario. È possibile utilizzare questa opzione se il backup viene liberato.

+
Specificare l'opzione -copy-id ogni volta che si specifica l'opzione -from-secondary. Se nel sistema di storage secondario sono presenti più backup, viene utilizzata l'opzione -copy-id per specificare quale copia di backup nello storage secondario utilizzare per montare il backup.

+

NOTE: Se si utilizza Data ONTAP in modalità 7, è necessario specificare un valore valido per l'opzione -copy-id. Tuttavia, se si utilizza Clustered Data ONTAP, l'opzione -copy-id non è richiesta.

* *-host host*
+
Specifica l'host su cui si desidera montare il backup.

* *-dump*
+
Raccoglie i file dump dopo l'operazione di montaggio riuscita o non riuscita.

* *-quiet*
+
Visualizza solo i messaggi di errore nella console. L'impostazione predefinita prevede la visualizzazione dei messaggi di errore e di avviso.

* *-dettagliato*
+
Visualizza messaggi di errore, di avviso e informativi nella console.




NOTE: Utilizzare questo comando solo se si utilizza uno strumento esterno come Oracle Recovery Manager (RMAN). SnapManager gestisce automaticamente il montaggio dei backup se si utilizza il comando smo backup restore per ripristinare il backup. Questo comando visualizza un elenco che mostra i percorsi in cui sono state montate le copie Snapshot. Questo elenco viene visualizzato solo quando viene specificata l'opzione -verbose.



== Esempio

Nell'esempio seguente viene montato il backup:

[listing]
----
smo backup mount -profile SALES1 -label full_backup_sales_May -verbose
SMO-13046 [INFO ]: Operation GUID 8abc013111b9088e0111b908a7560001 starting on Profile SALES1
SMO-08052 [INFO ]: Beginning to connect mount(s) [/mnt/ssys1/logs, /mnt/ssys1/data] from logical snapshot SMO_SALES1_hsdb1_F_C_1_8abc013111a450480111a45066210001.
SMO-08025 [INFO ]: Beginning to connect mount /mnt/ssys1/logs from snapshot SMO_SALES1_hsdb1_F_C_1_8abc013111a450480111a45066210001_0 of volume hs_logs.
SMO-08027 [INFO ]: Finished connecting mount /mnt/ssys1/logs from snapshot SMO_SALES1_hsdb1_F_C_1_8abc013111a450480111a45066210001_0 of volume hs_logs.
SMO-08025 [INFO ]: Beginning to connect mount /mnt/ssys1/data from snapshot SMO_SALES1_hsdb1_F_C_1_8abc013111a450480111a45066210001_0 of volume hs_data.
SMO-08027 [INFO ]: Finished connecting mount /mnt/ssys1/data from snapshot SMO_SALES1_hsdb1_F_C_1_8abc013111a450480111a45066210001_0 of volume hs_data.
SMO-08053 [INFO ]: Finished connecting mount(s) [/mnt/ssys1/logs, /mnt/ssys1/data] from logical snapshot SMO_SALES1_hsdb1_F_C_1_8abc013111a450480111a45066210001.
SMO-13037 [INFO ]: Successfully completed operation: Backup Mount
SMO-13048 [INFO ]: Operation Status: SUCCESS
SMO-13049 [INFO ]: Elapsed Time: 0:01:00.981
Operation Id [8abc013111b9088e0111b908a7560001] succeeded.
----
*Informazioni correlate*

xref:task_mounting_backups.adoc[Montaggio dei backup]
