---
permalink: unix-administration/reference_the_smosmsapbackup_show_command.html 
sidebar: sidebar 
keywords: backup, show, command, display, detail, information, backup, protection, status, retention, smo 
summary: È possibile utilizzare il comando show di backup per visualizzare informazioni dettagliate su un backup, tra cui lo stato di protezione, la classe di conservazione del backup e i backup sullo storage primario e secondario. 
---
= Il comando smo backup show
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare il comando show di backup per visualizzare informazioni dettagliate su un backup, tra cui lo stato di protezione, la classe di conservazione del backup e i backup sullo storage primario e secondario.



== Sintassi

[listing]
----

        smo backup show
-profile profile_name
[-label label \[-data \| -archivelogs\] \| \[-id id\]
\[-quiet \| -verbose\]
----


== Parametri

* *-profile_name*
+
Specifica il profilo per cui visualizzare i backup. Il profilo contiene l'identificatore del database e altre informazioni del database.

* etichetta **
+
Specifica l'etichetta del backup.

* *-dati*
+
Specifica i file di dati.

* *-archivelogs*
+
Specifica i file di log dell'archivio.

* id *-id*
+
Specifica l'ID del backup.

* *-quiet*
+
Visualizza solo i messaggi di errore nella console. L'impostazione predefinita prevede la visualizzazione dei messaggi di errore e di avviso.

* *-dettagliato*
+
Visualizza messaggi di errore, di avviso e informativi nella console, nonché informazioni su cloni e verifica.





== Esempio

L'esempio seguente mostra informazioni dettagliate sul backup:

[listing]
----
smo backup show -profile SALES1 -label BTNFS -verbose
Backup id: 8abc013111a450480111a45066210001
Backup status: SUCCESS
Primary storage resources: EXISTS
Protection sate: PROTECTED
Retention class: DAILY
Backup scope: FULL
Backup mode: OFFLINE
Mount status: NOT MOUNTED
Backup label: BTNFS
Backup comment:
RMAN Tag: SMO_BTNFS_1175283108815
Backup start time: 2007-03-30 15:26:30
Backup end time: 2007-03-30 15:34:13
Verification status: OK
Backup Retention Policy: NORMAL
Backup database: hsdb1
Checkpoint: 2700620
Tablespace: SYSAUX
Datafile: /mnt/ssys1/data/hsdb/sysaux01.dbf [ONLINE]
...
Control Files:
File: /mnt/ssys1/data/control03.ctl
...
Archive Logs:
File: /mnt/ssys1/data/archive_logs/2_131_626174106.dbf
...
Host: Host1
Filesystem: /mnt/ssys1/data
File: /mnt/ssys1/data/hsdb/SMOBakCtl_1175283005231_0
...
Volume: hs_data
Snapshot: SMO_HSDBR_hsdb1_F_C_1_
8abc013111a450480111a45066210001_0
File: /mnt/ssys1/data/hsdb/SMOBakCtl_1175283005231_0
...
Protected copies on Secondary Storage:
  14448939 - manow
  88309228 - graffe
----
*Informazioni correlate*

xref:task_viewing_backup_details.adoc[Visualizzazione dei dettagli del backup]
