---
permalink: unix-administration/reference_the_smosmsaprepository_update_command.html 
sidebar: sidebar 
keywords: command, repository, store, database, profile, associate, credentials, upgrade, snapmanager, install, smo, incomplete 
summary: Questo comando aggiorna il repository che memorizza i profili di database e le credenziali associate quando si aggiorna SnapManager. Ogni volta che si installa una nuova versione di SnapManager, è necessario eseguire il comando di aggiornamento del repository prima di poter utilizzare la nuova versione. È possibile utilizzare questo comando solo se nel repository non sono presenti comandi incompleti. 
---
= Il comando di aggiornamento del repository smo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Questo comando aggiorna il repository che memorizza i profili di database e le credenziali associate quando si aggiorna SnapManager. Ogni volta che si installa una nuova versione di SnapManager, è necessario eseguire il comando di aggiornamento del repository prima di poter utilizzare la nuova versione. È possibile utilizzare questo comando solo se nel repository non sono presenti comandi incompleti.



== Sintassi

[listing]
----

        smo repository update
-repository
-dbname repo_service_name
-host repo_host
-login -username repo_username
-port repo_port
[-force] [-noprompt]
\[-quiet \| -verbose\]
----


== Parametri

* *-repository*
+
Le opzioni che seguono -repository specificano i dettagli del database per il repository.

* *-dbname repo_service_name*
+
Specifica il nome del database in cui è memorizzato il repository. Utilizzare il nome globale o il SID.

* *-host repo_host*
+
Specifica il nome o l'indirizzo IP del computer host su cui viene eseguito il database del repository.

* *-login*
+
Avvia i dettagli di accesso al repository.

* *-nome utente repo_nome utente*
+
Specifica il nome utente necessario per accedere al database in cui è memorizzato il repository.

* *-port repo_port*
+
Specifica il numero di porta TCP utilizzato per accedere al database in cui è memorizzato il repository.

* *-force*
+
Tenta di forzare l'aggiornamento del repository. SnapManager richiede di eseguire un backup del repository corrente prima dell'aggiornamento.

* *-noprompt*
+
Non visualizza la richiesta prima di aggiornare il database del repository. L'opzione -noprompt consente di evitare la visualizzazione del prompt, semplificando l'aggiornamento dei repository mediante uno script.

* *-quiet*
+
Visualizza solo i messaggi di errore sulla console. L'impostazione predefinita prevede la visualizzazione dei messaggi di errore e di avviso.

* *-dettagliato*
+
Visualizza messaggi di errore, di avviso e informativi sulla console.





== Esempio di comando

Nell'esempio seguente viene aggiornato il repository nel database SALESDB.

[listing]
----
smo repository update -repository -dbname SALESDB
-host server1 -login -username admin -port 1521
----