---
permalink: unix-administration/reference_the_smosmsapclone_list_command.html 
sidebar: sidebar 
keywords: command, list, clone, database, given, profile, smo 
summary: Questo comando elenca i cloni del database per un determinato profilo. 
---
= Il comando smo clone list
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Questo comando elenca i cloni del database per un determinato profilo.



== Sintassi

[listing]
----

        smo clone list
-profile profile_name
-delimiter character
\[-quiet \| -verbose\]
----


== Parametri

* *-profile_name*
+
Specifica l'elenco dei cloni associati al profilo. Il profilo contiene l'identificatore del database e altre informazioni del database.

* carattere *-delimitatore*
+
Quando viene specificato questo parametro, il comando elenca gli attributi in ogni riga separati dal carattere specificato.

* *-quiet*
+
Visualizza solo i messaggi di errore sulla console. L'impostazione predefinita prevede la visualizzazione dei messaggi di errore e di avviso.

* *-dettagliato*
+
Visualizza messaggi di errore, di avviso e informativi sulla console.





== Esempio di comando

Nell'esempio seguente sono elencati i cloni del database nel profilo SALES1.

[listing]
----
smo clone list -profile SALES1 -verbose
----
[listing]
----
ID Status SID Host Label Comment
-------- ------- ----- ------- ---------- -------
8ab...01 SUCCESS hsdbc server1 back1clone test comment
----
*Informazioni correlate*

xref:task_viewing_a_list_of_clones.adoc[Visualizzazione di un elenco di cloni]
