---
permalink: unix-administration/reference_the_smosmsap_history_list_command.html 
sidebar: sidebar 
keywords: command, enable, list, history, detail, snapmanager, operation, smo 
summary: 'Questo comando consente di visualizzare un elenco dei dettagli della cronologia dell"operazione SnapManager.' 
---
= Il comando smo history list
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Questo comando consente di visualizzare un elenco dei dettagli della cronologia dell'operazione SnapManager.



== Sintassi

[listing]
----

        smo history list
-profile \{-name profile_name \[profile_name1, profile_name2\] \| -all
-repository
-login \[-password repo_password\]
-username repo_username
-host repo_host
-dbname repo_dbname
-port repo_port}
-operation \{-operations operation_name \[operation_name1, operation_name2\] \| -all\}
\[-delimiter character\]
\[-quiet \| -verbose\]
----


== Parametri

* *-profilo profilo*
+
Specifica il nome del profilo. Questo nome può contenere fino a 30 caratteri e deve essere univoco all'interno dell'host.

* *-repository*
+
Le opzioni che seguono -repository specificano i dettagli del database che memorizza il profilo.

* *-dbname repo_dbname*
+
Specifica il nome del database in cui è memorizzato il profilo. Utilizzare il nome globale o il SID.

* *-host repo_host*
+
Specifica il nome o l'indirizzo IP del computer host su cui viene eseguito il database del repository.

* *-login*
+
Avvia i dettagli di accesso al repository.

* *-nome utente repo_nome utente*
+
Specifica il nome utente necessario per accedere al database in cui è memorizzato il repository.

* *-port repo_port*
+
Specifica il numero di porta TCP utilizzato per accedere al database in cui è memorizzato il repository.

* *-operation {-operationsnome_operazione [nome_operazione 1, nome_operazione 2] | -all*
+
Specifica l'operazione SnapManager per la quale si configura la cronologia.

* *-quiet*
+
Visualizza solo i messaggi di errore sulla console. L'impostazione predefinita prevede la visualizzazione dei messaggi di errore e di avviso.

* *-dettagliato*
+
Visualizza messaggi di errore, di avviso e informativi sulla console.





== Esempio di comando

[listing]
----

          smo  history list -profile -name PROFILE1 -operation -operations backup -verbose
----