---
permalink: unix-administration/reference_the_smosmsap_operation_show_command.html 
sidebar: sidebar 
keywords: run, operation, show, command, list, summary, information, perform, specified, profile, smo, list 
summary: 'È possibile eseguire il comando show dell"operazione per elencare le informazioni di riepilogo di tutte le operazioni eseguite rispetto al profilo specificato. L"output elenca l"utente client (l"utente per il PC client) e l"utente effettivo (l"utente in SnapManager valido sull"host selezionato).' 
---
= Il comando show dell'operazione smo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile eseguire il comando show dell'operazione per elencare le informazioni di riepilogo di tutte le operazioni eseguite rispetto al profilo specificato. L'output elenca l'utente client (l'utente per il PC client) e l'utente effettivo (l'utente in SnapManager valido sull'host selezionato).



== Sintassi

[listing]
----

        smo operation show
-profile profile_name
\[-label label \| -id id\]
\[-quiet \| -verbose\]
----


== Parametri

* *-profile_name*
+
Specifica il nome del profilo. Questo nome può contenere fino a 30 caratteri e deve essere univoco all'interno dell'host.

* etichetta **
+
Specifica l'etichetta per l'operazione.

* id *-id*
+
Specifica l'identificativo dell'operazione.

* *-quiet*
+
Facoltativo: Visualizza solo i messaggi di errore nella console. L'impostazione predefinita prevede la visualizzazione dei messaggi di errore e di avviso.

* *-dettagliato*
+
Facoltativo: Visualizza messaggi di errore, di avviso e informativi nella console.





== Esempio

La seguente riga di comando mostra informazioni dettagliate su un'operazione:

[listing]
----
# smo operation show -profile myprofile -id ff8080811295eb1c011295eb28230001
----
[listing]
----
Operation Attempted
   Operation ID: ff8080811295eb1c011295eb28230001
   Type:RestoreFor profile: myprofile
   With Force: No
   Performed on backup
   Operation ID: ff8080811295eb1c011296eb23290001
   Label: mylabel
Operation Runtime Information
   Status: SUCCESS
   Start date: 2007-07-16 13:24:09 IST
   End date: 2007-07-16 14:10:10 IST
   Client user: amorrow
   Effective user: amorrow
Host
   Host Run upon: Host3
   Process ID: 3122
   SnapManager version: 3.3
Repository
   Connection: user1@SMOREPO/hotspur:1521
   Repository version: 3.3
Resources in use
   Volume:
     ssys1:/vol/luke_ES0_0 (FlexClone)
   Filesystems:
     /opt/NetApp/smo/mnt/-mnt_ssys1_luke_ES0_smo_e_es0_f_c_1_8abc0112129b0f81580001_0
----
*Informazioni correlate*

xref:task_viewing_operation_details.adoc[Visualizzazione dei dettagli delle operazioni]
