---
permalink: unix-administration/task_configuring_snapdrive_when_rbac_is_not_enabled.html 
sidebar: sidebar 
keywords: register, root, user, administrator, datafabric, manager, server, root, user, storage, system, snapdrive, rbac 
summary: 'Per abilitare la protezione dei dati, è necessario registrare l"utente root o l"amministratore del server DataFabric Manager e l"utente root del sistema storage con SnapDrive.' 
---
= Configurazione di SnapDrive quando RBAC non è attivato
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per abilitare la protezione dei dati, è necessario registrare l'utente root o l'amministratore del server DataFabric Manager e l'utente root del sistema storage con SnapDrive.

. Per aggiornare il server DataFabric Manager e le modifiche apportate direttamente sul sistema di storage dal database di destinazione, immettere il seguente comando:
+
host dfm discover storage_system

. Per registrare l'utente root o l'amministratore del server DataFabric Manager con SnapDrive, immettere il seguente comando:
+
Set di configurazione SnapDrive -dfm Administratordfm_host

. Per registrare l'utente root o l'amministratore del sistema storage con SnapDrive, immettere il seguente comando:
+
config. SnapDrive imposta root storage_system


