---
permalink: unix-administration/task_performing_backup_restore_and_clone_operations_using_prescript_and_post_scripts.html 
sidebar: sidebar 
keywords: script, initiating, backup, restore, clone, operation, snapmanager, display, task-enabling, command-line 
summary: 'È possibile utilizzare il proprio script durante l"avvio di un"operazione di backup, ripristino o clonazione. SnapManager visualizza una pagina di abilitazione attività nella procedura guidata di creazione backup, ripristino o ripristino o creazione clone, in cui è possibile selezionare lo script e fornire i valori per i parametri richiesti dallo script.' 
---
= Esecuzione di operazioni di backup, ripristino e clonazione utilizzando script prescrittivi e post-script
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare il proprio script durante l'avvio di un'operazione di backup, ripristino o clonazione. SnapManager visualizza una pagina di abilitazione attività nella procedura guidata di creazione backup, ripristino o ripristino o creazione clone, in cui è possibile selezionare lo script e fornire i valori per i parametri richiesti dallo script.

* Installare gli script dei plug-in nel percorso di installazione corretto di SnapManager.
* Verificare che i plug-in siano installati correttamente utilizzando il comando smo plugin check.
* Assicurarsi di utilizzare LA shell BASH.


Nell'interfaccia della riga di comando (CLI), elencare il nome dello script, selezionare i parametri e impostare i valori.

. Per verificare che si stia utilizzando LA shell BASH, immettere il seguente comando al prompt dei comandi:bash
+
In alternativa, è possibile immettere il comando quale-bash al prompt e utilizzare il comando output come parametro di avvio dello script.

+
La shell BASH funziona correttamente se non viene visualizzato un errore.

. Per l'operazione di backup, inserire l'opzione -taskspec e fornire il percorso assoluto del file XML delle specifiche dell'attività per eseguire un'attività di pre-elaborazione o post-elaborazione prima o dopo l'operazione di backup: smo backup create -profile_name {[-full {-online | -offline | -auto} [-retain {-hourly | [-daily | -settimanale | -mensile | -illimitato}] [-verify] | [-data [[-filesfiles [files]] | [-tablespaces-tablespaces-tablespaces] [-datalabellabellabellabel | -settimanale | -{-}-{-}--online | -verify [-sharly] -verify [-sharly] | -sharly] -sharly | -sharing [--untary | -sharly] -sharly | --untary [- [-protect | -noprotect | -protectnow] [-backup-destpath1 [,[path2]]] [-exclude-destpath1 [,path2]] [-prunelogs {-all | -untilSCNuntilSCN | -before {-dateyyy-MM-dd:mm:ss | -months | -days | -settimane | -she.spacune-spacune-spacune-spaces -}}-spacune-spacune-spaces-spaces] -share -share -share -}-spacing-spaces-spaces-spaces-spaces] -share -share-spacing--
+
Se l'operazione del plug-in di backup non riesce, vengono visualizzati solo il nome del plug-in e il codice di ritorno. Lo script del plug-in deve includere i messaggi di log e reindirizzare i messaggi ai file di log definiti dall'utente.

. Per l'operazione di ripristino del backup, Inserire l'opzione -taskspec e fornire il percorso assoluto del file XML della specifica del task per eseguire una pre-elaborazione o un'attività di post-elaborazione prima o dopo l'operazione di ripristino:smo backup restore -profileprofile_name {-labortologic <label> | -restortunch <id>} {-<files>|-tablespacenglos <tablespaces> | -complete | -controlfiles} [-recover {-alllogs | -<until> | -final | -<restorespec>}] -from-secondary [-temp-volume <temp_volume>] [-copy-idid][-<taskspec>] [-verify][-force] backup restore -fast [require | override | fallback | off] [-preview] -dump [-quiet | -verbose]
+
Se l'operazione di ripristino del plug-in non riesce, vengono visualizzati solo il nome del plug-in e il codice di ritorno. Lo script del plug-in deve includere i messaggi di log e reindirizzare i messaggi ai file di log definiti dall'utente.

. Per l'operazione di creazione del clone, immettere l'opzione -taskspec e fornire il percorso assoluto del file XML della specifica del task per eseguire una pre-elaborazione o un'attività di post-elaborazione prima o dopo l'operazione di clonazione: smo create -profileprofile_name {-backup-labelbackup_name | -backup-data <backup-id>| -current} -newsidnew_sid-clonespecfull_path_to_clonespecfile [-reservaresfile] [-reservaresfile] [-lobosclone <host> <id>] [-laboschet] [-comaskde-<label> <taskspec>-quiet-<yes, no, inherit> <comment>-{]]
+
Se l'operazione del plug-in clone non riesce, vengono visualizzati solo il nome del plug-in e il codice di ritorno. Lo script del plug-in deve includere i messaggi di log e reindirizzare i messaggi ai file di log definiti dall'utente.





== Esempio di creazione di un backup utilizzando il file XML delle specifiche dell'attività

[listing]
----
smo backup create -profile SALES1 -full -online -taskspec sales1_taskspec.xml -force -verify
----