---
permalink: unix-administration/task_using_snapmanager_for_oracle_to_create_the_database_profile_and_assign_a_protection_policy.html 
sidebar: sidebar 
keywords: create, profile, snapmanager, oracle, enable, protect, client, payroll, paydb 
summary: È necessario creare un profilo in SnapManager per Oracle, attivare la protezione nel profilo e assegnare un criterio di protezione per creare un backup protetto. 
---
= Utilizzo di SnapManager per Oracle per creare il profilo del database e assegnare una policy di protezione
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È necessario creare un profilo in SnapManager per Oracle, attivare la protezione nel profilo e assegnare un criterio di protezione per creare un backup protetto.

Un profilo contiene informazioni sul database gestito, incluse le credenziali, le impostazioni di backup e le impostazioni di protezione per i backup. Dopo aver creato un profilo, non è necessario specificare i dettagli del database ogni volta che si esegue un'operazione. Un profilo può fare riferimento a un solo database, ma lo stesso database può essere referenziato da più profili.

. Accedere al client SnapManager per Oracle.
. Nella struttura dei repository, fare clic con il pulsante destro del mouse sull'host e selezionare *Create Profile* (Crea profilo).
. Nella pagina Profile Configuration Information (informazioni configurazione profilo), inserire i dettagli del profilo e fare clic su *Next* (Avanti).
+
È possibile inserire le seguenti informazioni:

+
** Nome del profilo: Payroll_prod2
** Password del profilo: Payroll123
** Commento: Database Payroll di produzione


. Nelle pagine Database Configuration Information (informazioni configurazione database), immettere i dettagli del database e fare clic su *Next* (Avanti).
+
È possibile inserire le seguenti informazioni:

+
** Nome database: PAYDB
** SID del database: Payrolldb
** Host database: Accettare l'impostazione predefinita. Poiché si sta creando un profilo da un host nella struttura del repository, SnapManager visualizza il nome host.
** Host account, che rappresenta l'account utente Oracle: oracle
** Host Group, che rappresenta il gruppo Oracle: dba


. Nella pagina Database Connection Information (informazioni connessione database), fare clic su *Use database Authentication* (Usa autenticazione database) per consentire agli utenti di autenticarsi utilizzando le informazioni del database.
. Inserire i dettagli di connessione al database e fare clic su *Avanti*.
+
È possibile inserire le seguenti informazioni:

+
** SYSDBA Privileged User Name (Nome utente privilegiato SYSDBA), che rappresenta l'amministratore del database di sistema con privilegi amministrativi: SYS
** Password (SYSDBA password): oracle
** Porta per la connessione all'host del database: 1521


. Nella pagina RMAN Configuration Information (informazioni di configurazione RMAN), fare clic su *Do not use RMAN* (non utilizzare RMAN) e fare clic su *Next* (Avanti).
+
Oracle Recovery Manager (RMAN) è uno strumento Oracle che consente di eseguire il backup e il ripristino dei database Oracle utilizzando il rilevamento a livello di blocco.

. Nella pagina Snapshot Naming Information, specificare una convenzione di denominazione per le istantanee associate a questo profilo selezionando Variables (variabili).
+
La variabile smid crea un identificatore di snapshot univoco.

+
Effettuare le seguenti operazioni:

+
.. Nell'elenco Variable Token (token variabile), selezionare usertext e fare clic su *Add* (Aggiungi).
.. Inserire payroll.techco.com_ come nome host e fare clic su *OK*.
.. Fare clic su *sinistra* fino a visualizzare il nome host subito dopo smo nella casella Format (formato).
.. Fare clic su *Avanti*.


+
La convenzione di naming Snapshot di smo_hostname_smoprofile_dbsid_scope_mode_smid diventa "smo_payroll.techco.com_payroll_prod2_payrolldb_f_a_x" (dove "f" indica un backup completo, "a" indica la modalità automatica e "x" rappresenta L'SMID univoco).

. Selezionare *Protection Manager Protection Policy*.
+
La *Protection Manager Protection Policy* consente di selezionare una policy di protezione configurata utilizzando la NetApp Management Console.

. Selezionare *TechCo Payroll Data: Backup* come policy di protezione dalle policy di protezione recuperate da NetApp Management Console e fare clic su *Avanti*.
. Nella pagina Perform operation (Esegui operazione), verificare le informazioni e fare clic su *Create* (Crea).
. Fare clic su *Dettagli operazione* per visualizzare le informazioni sull'operazione di creazione del profilo e sull'idoneità al ripristino basato sul volume.
+
** L'assegnazione di una policy di protezione della console di gestione NetApp al profilo del database crea automaticamente un set di dati non conforme, visibile all'operatore della console di gestione NetApp, con la convenzione di denominazione smo_<hostname>_<profilename> o, in questo esempio, smo_payroll.tech.com_PAYDB.
** Se il profilo non è idoneo per il ripristino del volume (chiamato anche "ripristino rapido"), si verifica quanto segue:
+
*** La scheda *risultati* indica che la creazione del profilo è riuscita e che si sono verificati degli avvisi durante l'operazione.
*** La scheda *Dettagli operazione* include un registro DI AVVISO che indica che il profilo non è idoneo per il ripristino rapido e spiega il motivo.





