---
permalink: unix-administration/task_adding_storage_systems_to_the_snapmanager_server_host.html 
sidebar: sidebar 
keywords: add, storage, system, operating, clustered, data, ontap, snapmanager, server, host, enable, autosupport 
summary: 'Per abilitare AutoSupport, è necessario aggiungere i sistemi storage che operano in Clustered Data ONTAP all"host del server SnapManager. In SnapManager 3.3 e versioni precedenti, AutoSupport era supportato solo sui sistemi storage che operavano in 7-Mode.' 
---
= Aggiunta di sistemi storage che operano in Clustered Data ONTAP all'host del server SnapManager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per abilitare AutoSupport, è necessario aggiungere i sistemi storage che operano in Clustered Data ONTAP all'host del server SnapManager. In SnapManager 3.3 e versioni precedenti, AutoSupport era supportato solo sui sistemi storage che operavano in 7-Mode.

. Aggiungere sistemi storage che operano in Clustered Data ONTAP all'host del server SnapManager.
+
|===
| Se... | Quindi eseguire il seguente comando... 


 a| 
La macchina virtuale per lo storage di amministrazione (SVM, precedentemente nota come Vserver) opera in Clustered Data ONTAP
 a| 
set di configurazione SnapDrive -cserver nome_utente



 a| 
SVM opera in Clustered Data ONTAP
 a| 
set di configurazione SnapDrive -nome_utente_vserver

|===

