---
permalink: unix-administration/task_mounting_backups.html 
sidebar: sidebar 
keywords: snapmanager, automatic, handle, mount, backup, available, host, scenario, rman, 7-mode 
summary: 'SnapManager gestisce automaticamente il montaggio di un backup per renderlo disponibile all"host. È inoltre possibile montare i backup in scenari in cui si utilizza un tool esterno, ad esempio Oracle Recovery Manager (RMAN), per accedere ai file nel backup.' 
---
= Montaggio dei backup
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager gestisce automaticamente il montaggio di un backup per renderlo disponibile all'host. È inoltre possibile montare i backup in scenari in cui si utilizza uno strumento esterno, ad esempio Oracle Recovery Manager (RMAN), per accedere ai file nel backup.

Se si utilizza RMAN, è necessario utilizzare l'operazione di montaggio per modificare lo stato di un backup (che consente l'accesso) e l'operazione di disinstallazione per modificare lo stato di un backup (che rimuove l'accesso).

Il comando smo backup mount visualizza un elenco di percorsi in cui sono state montate le copie Snapshot costituite dal backup.

È possibile utilizzare l'opzione -from-secondary per montare il backup dallo storage secondario. Se non si utilizza questa opzione, SnapManager installa il backup dallo storage primario.

Specificare l'opzione -copy-id ogni volta che si specifica l'opzione -from-secondary. Se nel sistema di storage secondario sono presenti più backup, viene utilizzata l'opzione -copy-id per specificare quale copia di backup nello storage secondario utilizzare per montare il backup.6


NOTE: Se si utilizza Data ONTAP in modalità 7, è necessario specificare un valore valido per l'opzione -copy-id. Tuttavia, se si utilizza Clustered Data ONTAP, l'opzione -copy-id non è richiesta.

Se si sta montando un backup del database su un host remoto, è necessario assicurarsi che le credenziali di Automatic Storage Management (ASM) siano le stesse su entrambi gli host.


NOTE: È possibile raccogliere i file dump dopo un'operazione di montaggio di backup riuscita o non riuscita.

. Per attivare un backup, immettere il seguente comando:
`smo backup mount -profile profile_name {labellabel [data | -archivelogs] | -idid} [-host-host] [-from-secondary [-copy-id id]] [-dump] [-quiet | -verbose]`


*Informazioni correlate*

xref:reference_the_smosmsapbackup_mount_command.adoc[Il comando di montaggio del backup smo]
