---
permalink: unix-administration/task_customizing_the_email_subject_for_an_existing_profile.html 
sidebar: sidebar 
keywords: snapmanager, enable, customize, email, subject, pattern, exist, profile, smo 
summary: 'SnapManager consente di personalizzare il modello di oggetto dell"e-mail per un profilo esistente aggiornando tale profilo. Questo modello di soggetto personalizzato è applicabile solo al profilo aggiornato.' 
---
= Personalizzazione dell'oggetto e-mail per un profilo esistente
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager consente di personalizzare il modello di oggetto dell'e-mail per un profilo esistente aggiornando tale profilo. Questo modello di soggetto personalizzato è applicabile solo al profilo aggiornato.

. Immettere il seguente comando: smo profile update -profileprofile [-profile-passwordprofile_password][-database-dbnamedb_dbname-host db_host [-siddb_sid] [-login -usernamedb_username-password_db_port db_port] [{-rman{-controlfile | {-login -nomeaccount [-nomeutente] [-nomeutente]_nsutaprotect] [-nomeaccount [-nomeutente]-nomeaccount [-nomeutente]_email [-nomeutente]_nsnomeutente]_nsnomeaccount [-nomeutente]_nsnomeaccount [-nomeutente]_nsnomeutente]_email [-nomeutente]_nsnomeutente]_email [-nomeutente]_nsnomeutente]_nsnomeutente]_password] [-nomeutente] [-}}}]_nsnomeutente]_password [-]_nsnomeutente_password


Nell'esempio seguente viene mostrato un modello di oggetto dell'e-mail:

[listing]
----

smo profile update -profile sales1 -profile-password sales1 -repository -dbname repo2 -host 10.72.197.133 -port 1521 -login -username admin2 -database -dbname DB1 -host 10.72.197.142 -sid DB1
-osaccount oracle -osgroup dba -profile-notification -success -email admin@org.com -subject {profile}_{operation-name}_{db-sid}_{db-host}_{start-date}_{end-date}_{status}
----