---
permalink: unix-administration/task_changing_the_retention_policy_default_behavior.html 
sidebar: sidebar 
keywords: backup, expire, based, retention, policy, snapmanager, determine, delete, backup, setting, policy, default, behavior 
summary: 'Quando un backup scade in base al criterio di conservazione, SnapManager determina se eliminare il backup in base alle impostazioni di conservazione. L"eliminazione dei backup è il comportamento predefinito. È possibile modificare questo comportamento predefinito e scegliere di liberare i backup non protetti.' 
---
= Modifica del comportamento predefinito del criterio di conservazione
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando un backup scade in base al criterio di conservazione, SnapManager determina se eliminare il backup in base alle impostazioni di conservazione. L'eliminazione dei backup è il comportamento predefinito. È possibile modificare questo comportamento predefinito e scegliere di liberare i backup non protetti.

Per impostazione predefinita, SnapManager elimina o libera i backup a seconda che siano protetti o meno come segue:

* Per i backup protetti, SnapManager libera i backup locali quando scadono.
* Per i backup non protetti, SnapManager elimina i backup locali alla scadenza.
+
È possibile modificare questo comportamento predefinito.



Per i backup protetti, SnapManager non prende in considerazione quanto segue per determinare se eliminare la copia locale:

* Il backup sullo storage secondario non è riuscito o è in corso la protezione.
+
Ciò consente il trasferimento dei backup sullo storage secondario prima dell'applicazione del criterio di conservazione.

* La copia è stata successivamente eliminata dallo storage secondario.
+
.. Accedere alla seguente posizione predefinita:
+
percorso/proprietà di installazione smo predefinito/smo.config

.. Modificare il file smo.config.
.. Impostare la proprietà Retain.alwaysFreeExpiredBackups nel file smo.config su true.
+
Ad esempio, Retain.alwaysFreeExpiredBackups = true





*Informazioni correlate*

xref:reference_the_smosmsapbackup_update_command.adoc[Il comando smo backup update]
