---
permalink: unix-administration/task_verifying_database_backups.html 
sidebar: sidebar 
keywords: backup, verify, command, block, database, corrupt, operation, invoke, oracle, smo 
summary: 'È possibile utilizzare il comando di verifica del backup per verificare che i blocchi nel backup del database non siano corrotti. L"operazione di verifica richiama l"utility Oracle Database Verify per ogni file di dati nel backup.' 
---
= Verifica dei backup del database
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare il comando di verifica del backup per verificare che i blocchi nel backup del database non siano corrotti. L'operazione di verifica richiama l'utility Oracle Database Verify per ogni file di dati nel backup.

SnapManager consente di eseguire l'operazione di verifica in qualsiasi momento utile per l'utente e per gli utenti del sistema. È possibile eseguire la verifica subito dopo aver creato il backup. Specificare il profilo contenente il backup e l'etichetta o l'ID del backup creato.


NOTE: È possibile specificare -dump per raccogliere i file dump dopo l'operazione di verifica del backup.

. Immettere il seguente comando:
`smo backup verify -profile profile_name [-label label | -idid] [-force] [ -dump] [-quiet | -verbose]`


*Informazioni correlate*

xref:reference_the_smosmsapbackup_verify_command.adoc[Il comando di verifica del backup smo]
