---
permalink: unix-administration/task_protecting_database_backups_on_secondary_storage.html 
sidebar: sidebar 
keywords: snapmanager, protect, backup, copies, secondary, tertiary, storage, system, smo 
summary: È possibile utilizzare SnapManager per proteggere le copie di backup su sistemi di storage secondari o terziari. 
---
= Protezione dei backup dei database su storage secondario o terzo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare SnapManager per proteggere le copie di backup su sistemi di storage secondari o terziari.

. Immettere il seguente comando:
`smo backup create -profile profile_name {[-full {-online | -offline | -auto} [-retain {-hourly | -daily | -weekly | -monthly | -unlimited}] [-verify] | [-data [[-filesfiles [files]] | [-tablespaces-tablespaces [-tablespaces]] [-datalabellabel] {-online | -offline | -auto} [-retain {-hourly | [-daily | -weekly | -monthly | -unlimited]} [-verify] | [-archivelogs [-labellabel] [-commentcomment] [-snapvaultlabelSnapVault_label][-protect | -noprotect | -protectnow] [-backup-destpath1 [,[path2]]] [-exclude-destpath1 [,path2]]] [-prunelogs {-all | -untilSCNuntilSCN | -until-date yyyy-MM-dd:HH:mm:ss | -before {-months | -days | -weeks | -hours}} -prune-destprune_dest1,[prune_dest2]] [-taskspectaskspec]} [-dump] [-force] [-quiet | -verbose]`
+
|===
| Se si desidera... | Quindi... 


 a| 
*Creare un backup di un database online o offline, invece di consentire a SnapManager di gestire se è online o offline*
 a| 
Specificare l'opzione -offline o -online per creare un backup del database offline o online. Se si utilizza l'opzione -offline o -online, non è possibile utilizzare l'opzione -auto.



 a| 
*Lasciare che SnapManager gestisca il backup di un database, indipendentemente dal fatto che sia online o offline*
 a| 
Specificare l'opzione -auto. Se si utilizza l'opzione -auto, non è possibile utilizzare l'opzione -offline o -online.



 a| 
*Aggiungere un commento sul backup*
 a| 
Specificare l'opzione -comment, seguita dalla stringa di descrizione.



 a| 
*Forzare il database nello stato in cui è stato specificato il backup, indipendentemente dallo stato in cui si trova attualmente*
 a| 
Specificare l'opzione -force.



 a| 
*Verificare il backup al momento della creazione*
 a| 
Specificare l'opzione -verify.



 a| 
*Creare un backup sullo storage secondario*
 a| 
Specificare l'opzione -Protect.

** Se si utilizza ONTAP e si desidera proteggere immediatamente il backup sullo storage secondario, specificare l'opzione -Protect.
+

NOTE: L'opzione -protectnow non è applicabile in Clustered Data ONTAP.

** Se si utilizza Data ONTAP in 7-Mode e si desidera proteggere immediatamente il backup sullo storage secondario sovrascrivendo il programma di protezione di Protection Manager, specificare l'opzione -protectnow.
** Per impedire il backup sullo storage secondario, specificare l'opzione -noprotect. Se si utilizza ONTAP e si seleziona il criterio di protezione _SnapManager_cDOT_Vault_ durante la creazione del profilo, è necessario specificare l'opzione -snapvaultlabel. È necessario fornire l'etichetta SnapMirror specificata nelle regole del criterio SnapMirror durante l'impostazione della relazione SnapVault come valore.




 a| 
*Specificare i valori della classe di conservazione*
 a| 
Specificare l'opzione -retain e indicare se il backup deve essere conservato a seconda di una delle seguenti classi di conservazione:

** orario
** giornaliero
** settimanale
** mensile
** -Unlimited se non si specifica la classe di conservazione, SnapManager utilizza -hourly per impostazione predefinita.


|===




== Esempi

Il seguente comando protegge un backup del database:

[listing]
----
smo backup create -profile PAYDB -protect -retain -daily -full auto -label full_bkup_sales
----
Il seguente comando protegge immediatamente un backup del database:

[listing]
----
smo backup create -profile PAYDB -protectnow -retain -daily -full auto -label full_bkup_sales
----