---
permalink: unix-administration/task_cloning_protected_backups.html 
sidebar: sidebar 
keywords: snapmanager, clone, copy, backup, protect, cloning, san, nas, ontap, 7-mode 
summary: È possibile utilizzare SnapManager per clonare una copia di un backup protetto. 
---
= Clonazione di backup protetti
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare SnapManager per clonare una copia di un backup protetto.

L'host (selezionato per il clone) deve avere accesso allo storage secondario utilizzando lo stesso protocollo di storage (ad esempio, SAN o NAS).

È possibile utilizzare l'opzione -from-secondary per specificare che si desidera clonare dallo storage secondario.

Specificare l'opzione -copy-id ogni volta che si specifica l'opzione -from-secondary. Se nel sistema di storage secondario sono presenti più backup, viene utilizzata l'opzione -copy-id per specificare quale copia di backup nello storage secondario deve essere utilizzata per la clonazione.


NOTE: Se si utilizza Data ONTAP in modalità 7, è necessario specificare un valore valido per l'opzione -copy-id. Tuttavia, se si utilizza Clustered Data ONTAP, l'opzione -copy-idoption non è richiesta.

L'eliminazione dei cloni dei backup protetti sui sistemi di storage secondari potrebbe non riuscire. Questo problema si verifica quando l'ora di sistema dei sistemi di storage primario e secondario non è sincronizzata.

. Creare un clone di una copia di backup protetta: Clone smo create -backup-labelbackup_name-newsidnew_sid-labelclone_label-profileprofile_name-clonespecfull_path_to_clonespecfile-from-secondary -copy-idid




== Esempio

[listing]
----
smo clone create -label testdb_clone_clstest
-profile sys_db_finance -from-secondary -copy-id 3042 sys_db_finance_sept_08
----