---
permalink: unix-administration/task_configuring_snapmanager_for_oracle_with_veritas_file_system.html 
sidebar: sidebar 
keywords: snapmanager, install, solaris, configure, veritas, storage, foundation, oracle, rac, sfrac, environment 
summary: 'Quando SnapManager è installato su Solaris, è possibile configurare SnapManager per il supporto dell"ambiente.' 
---
= Configurazione di SnapManager per il supporto dell'ambiente Veritas SFRAC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando SnapManager è installato su Solaris, è possibile configurare SnapManager per supportare l'ambiente TRAC di Veritas Storage Foundation per Oracle.

* Sull'host devono essere installati Solaris, utility host e Veritas.
+
.. Creare un gruppo di dischi condivisi e un file system per SnapManager utilizzando SnapDrive per UNIX in modo che i file system siano montati contemporaneamente su entrambi i nodi dei cluster di applicazioni reali (RAC).
+
Per informazioni su come creare un gruppo di dischi e un file system condivisi, consultare la documentazione di SnapDrive.

.. Installare e configurare il database Oracle da montare sui file system condivisi.
.. Avviare un'istanza di database su un nodo qualsiasi del RAC.




http://mysupport.netapp.com/["Documentazione sul sito di supporto NetApp: mysupport.netapp.com"]
