---
permalink: unix-administration/task_configuring_e_mail_notification_for_an_existing_profile.html 
sidebar: sidebar 
keywords: updating, profile, configure, receive, email, notification, completion, database, operation, exist, comma-seperated, list 
summary: 'Quando si aggiorna un profilo, è possibile configurare per ricevere una notifica via email al completamento dell"operazione di database.' 
---
= Configurazione della notifica e-mail per un profilo esistente
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando si aggiorna un profilo, è possibile configurare per ricevere una notifica via email al completamento dell'operazione di database.

* È necessario configurare l'indirizzo e-mail da cui vengono inviati gli avvisi.
* È necessario inserire un singolo indirizzo e-mail o più indirizzi e-mail a cui verranno inviati gli avvisi.
+
È possibile utilizzare un elenco separato da virgole per più indirizzi. Assicurarsi che non vi sia spazio tra la virgola e l'indirizzo e-mail successivo. In alternativa, è possibile aggiungere un oggetto all'e-mail.

+
.. Immettere il seguente comando:smo profile update -profileprofile [-profile-passwordprofile_password][-database-dbnamedb_dbname-host db_host [-siddb_sid] [-login -usernamedb_username-password_db_port db_port] [{-rman{-controlfile | {-login -nomeaccount [-nomeutente] [-nomeutente]_nsutaprotect] [-nomeaccount [-nomeutente]-nomeaccount [-nomeutente]_email [-nomeutente]_nsnomeutente]_nsnomeaccount [-nomeutente]_nsnomeaccount [-nomeutente]_nsnomeutente]_email [-nomeutente]_nsnomeutente]_email [-nomeutente]_nsnomeutente]_nsnomeutente]_password] [-nomeutente] [-}}}]_nsnomeutente]_password_password_chiave_chiave_chiave_] [
+
È possibile utilizzare l'opzione Success per ricevere una notifica solo per le operazioni di database riuscite e l'opzione failure per ricevere una notifica solo per le operazioni di database non riuscite.




