---
permalink: unix-administration/task_customizing_e_mail_subject_for_a_new_profile.html 
sidebar: sidebar 
keywords: customize, email, subject, new, profile, create 
summary: 'È possibile personalizzare l"oggetto dell"e-mail per il nuovo profilo al momento della creazione.' 
---
= Personalizzazione dell'oggetto dell'e-mail per un nuovo profilo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile personalizzare l'oggetto dell'e-mail per il nuovo profilo al momento della creazione.

Puoi personalizzare l'oggetto dell'email usando il modello{profile}_{nome-operazione}_{db-sid}_{db-host}_{data-inizio}_{data-fine}_{stato} o inserisci il tuo testo.

|===
| Nome della variabile | Descrizione | Valore di esempio 


 a| 
profilo
 a| 
Nome del profilo utilizzato per l'operazione del database
 a| 
PROF1



 a| 
nome-operazione
 a| 
Nome operazione database
 a| 
Backup, backup dei dati, backup dei dati e dei registri di archiviazione



 a| 
db-sid
 a| 
SID del database
 a| 
DB1



 a| 
db-host
 a| 
Nome del server host
 a| 
Host



 a| 
data di inizio
 a| 
Ora di inizio dell'operazione del database nel formato mmdd:hh:ss yyyy
 a| 
Aprile 27 21:00:45 PST 2012



 a| 
data di fine
 a| 
Ora di fine dell'operazione del database nel formato mmdd:hh:ss yyyy
 a| 
Aprile 27 21:10:45 PST 2012



 a| 
stato
 a| 
Stato operativo del database
 a| 
Successo

|===
Se non si fornisce alcun valore per le variabili, SnapManager visualizza il seguente messaggio di errore: Valori mancanti -subject.

. Immettere il seguente comando: smo profile create -profileprofile [-profile-passwordprofile_password] -repository-dbnamerepo_service_name-hostrepo_host-portrepo_port-login-username-username-username_username_name_db_host [-siddsdpub] [-nomespaint.com] {-{-name] [-nomespaint.com] [-} }]-nomes.com] [-nomes.com]--nomes.com]-nomes.com] [--nomes.com] [-nomes.com]-nomeself] [-nomeself]_nomeself] [-nomeself-] [-nomeself-nomeself]_nome_nome_nome_] [-nomeself] [-nomeself] [-nomeself]_nome_nome_nome_nome_] [-nomeself]] [-]_nome_nome_nome_nome_nomeself]_nome


Di seguito viene riportato un esempio che mostra il modello dell'oggetto dell'e-mail:

[listing]
----

smo profile create -profile sales1 -profile-password admin1 -repository -dbname repo2 -host 10.72.197.133 -port 1521 -login -username admin2 -database -dbname DB1 -host 10.72.197.142 -sid DB1
-osaccount oracle -osgroup dba -profile-notification -success -email admin@org.com -subject {profile}_{operation-name}_{db-sid}_{db-host}_{start-date}_{end-date}_{status}
----