---
permalink: unix-administration/task_updating_target_database_hostname_associated_with_a_profile.html 
sidebar: sidebar 
keywords: snapmanager, 3.2, oracle, provide, ability, update, host, name, target, database, snapmanager, profile, smo 
summary: SnapManager 3.2 o versione successiva per Oracle consente di aggiornare il nome host del database di destinazione nel profilo SnapManager. 
---
= Aggiornamento del nome host del database di destinazione associato a un profilo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager (3.2 o versione successiva) per Oracle consente di aggiornare il nome host del database di destinazione nel profilo SnapManager.

* La home directory dell'utente locale deve essere consapevole delle mappature da profilo a repository.
* Le sessioni dell'interfaccia grafica utente (GUI) di SnapManager devono essere chiuse.
* In un ambiente RAC (Real Application Clusters), i cloni o i backup montati disponibili sull'host specificato nel profilo devono essere cancellati e rimossi.


È possibile aggiornare il profilo con il nuovo nome host utilizzando solo l'interfaccia CLI.

*Scenari non supportati per la modifica del nome host del database di destinazione nel profilo*

I seguenti scenari non sono supportati per la modifica del nome host del database di destinazione nel profilo:

* Modifica del nome host del database di destinazione mediante l'interfaccia grafica di SnapManager
* Eseguire il rollback del database del repository dopo aver aggiornato il nome host del database di destinazione del profilo
* Aggiornamento di più profili per un nuovo nome host del database di destinazione mediante un singolo comando
* Modifica del nome host del database di destinazione quando è in esecuzione un'operazione SnapManager
* Modifica del nome host del database di destinazione se SnapManager è installato su Solaris e se i numeri delle unità logiche (LUN) del database vengono creati utilizzando il file system montato su host con stack SVM.



NOTE: Dopo aver aggiornato il nome host del database di destinazione nel profilo, viene modificato solo il nome host del database di destinazione. Tutti gli altri parametri di configurazione impostati sul profilo vengono conservati.

Dopo aver aggiornato il nuovo nome host del database di destinazione in un profilo abilitato alla protezione, vengono conservati gli stessi set di dati e criteri di protezione per il profilo aggiornato.

Dopo aver modificato il nome host per l'host di destinazione, è necessario aggiornare il nome host per tutti i profili protetti esistenti prima di creare i nuovi profili protetti. Per aggiornare il nome host di un profilo, eseguire il comando di aggiornamento del profilo smo.

Dopo aver aggiornato il nome host del database di destinazione, non è possibile rimuovere o separare il clone o smontare il backup se il clone o il backup montato non sono disponibili nel nuovo host. In tali scenari, l'esecuzione delle operazioni SnapManager dal nuovo host comporta errori e voci obsolete nell'host precedente. Per eseguire operazioni SnapManager, è necessario ripristinare il nome host precedente utilizzando l'aggiornamento del profilo.

. Immettere il seguente comando:
`smo profile update -profileprofile [-profile-passwordprofile_password][-database-dbnamedb_dbname-hostdb_host [-siddb_sid] [-login-usernamedb_username-passworddb_password-portdb_port]] [{-rman{-controlfile | {-login-usernamerman_username-passwordrman_password-tnsnamerman_tnsname}}} | -remove-rman]-osaccountosaccount-osgrouposgroup [-retain [-hourly [-countn] [-durationm]] [-daily [-countn] [-durationm]] [-weekly [-countn] [-durationm]] [-monthly [-countn] [-durationm]]] [-commentcomment][-snapname-patternpattern][[-protect [-protection-policypolicy_name]]| [[-noprotect]] [-summary-notification] [-notification [-success-emailemail_address1, email_address2-subjectsubject_pattern] [-failure-emailemail_address1, email_address2-subjectsubject_pattern]] [-separate-archivelog-backups-retain-archivelog-backups-hourshours | -daysdays | -weeksweeks| -monthsmonths [-protect [-protection-policypolicy_name] | -noprotect] [-include-with-online-backups | -no-include-with-online-backups]] [-dump]`
+
Le altre opzioni per questo comando sono le seguenti:

+
[-force] [-noprompt]

+
|===


| Se si desidera... | Quindi... 


 a| 
*Modificare il nome host del database di destinazione*
 a| 
Specificare -hostnew_db_host

|===
. Per visualizzare il nome host del database di destinazione del profilo, immettere il seguente comando:
`smo profile show`

