---
permalink: unix-installation-cmode/reference_product_overview.html 
sidebar: sidebar 
keywords: snapmanager, oracle, automate, simplifies, complex, manual, time-consuming, process, associate, backup, recovery, clone, ontap, snapvault, disk, rac 
summary: SnapManager per Oracle automatizza e semplifica i processi complessi, manuali e lunghi associati al backup, al ripristino e alla clonazione dei database Oracle. È possibile utilizzare SnapManager con la tecnologia SnapMirror di Data ONTAP per creare copie dei backup su un altro volume e con la tecnologia Data ONTAP SnapVault per archiviare i backup su disco in modo efficiente. 
---
= Panoramica del prodotto
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager per Oracle automatizza e semplifica i processi complessi, manuali e lunghi associati al backup, al ripristino e alla clonazione dei database Oracle. È possibile utilizzare SnapManager con la tecnologia SnapMirror di Data ONTAP per creare copie dei backup su un altro volume e con la tecnologia Data ONTAP SnapVault per archiviare i backup su disco in modo efficiente.

SnapManager si integra con le tecnologie Oracle native come Oracle Real Application Clusters (Oracle RAC), Automatic Storage Management (ASM) e Direct NFS su protocolli FC, iSCSI e NFS. Facoltativamente, i backup creati utilizzando SnapManager possono essere catalogati con Oracle Recovery Manager (RMAN) per conservare le informazioni di backup; questi backup possono essere utilizzati in seguito nelle operazioni di ripristino a livello di blocco o tablespace point-in-time.



== Punti salienti di SnapManager

SnapManager offre un'integrazione perfetta con i database Oracle sull'host UNIX e con le tecnologie NetApp Snapshot, SnapRestore e FlexClone sul back-end Offre un'interfaccia utente (UI) di facile utilizzo e un'interfaccia a riga di comando (CLI) per le funzioni amministrative.

SnapManager consente di eseguire le seguenti operazioni di database e gestire i dati in modo efficiente:

* Creazione di backup efficienti in termini di spazio sullo storage primario o secondario
+
SnapManager consente di eseguire il backup dei file di dati e di archiviare i file di log separatamente.

* Pianificazione dei backup
* Ripristino di database completi o parziali mediante un'operazione di ripristino basata su file o volume
* Ripristino dei database mediante il rilevamento, il montaggio e l'applicazione dei file di log di archiviazione dai backup
* Eliminazione dei file di log dell'archivio dalle destinazioni dei log dell'archivio durante la creazione di backup dei soli log dell'archivio
* Conservazione automatica di un numero minimo di backup del log di archiviazione mantenendo solo i backup che contengono file di log di archiviazione univoci
* Monitoraggio dei dettagli delle operazioni e generazione di report
* Verifica dei backup per garantire che i backup siano in un formato a blocchi valido e che nessuno dei file di backup sia corrotto
* Mantenere una cronologia delle operazioni eseguite sul profilo del database
+
Un profilo contiene informazioni sul database che deve essere gestito da SnapManager.

* Protezione dei backup sui sistemi storage secondari.
* Creazione di cloni di backup efficienti in termini di spazio su storage primario o secondario
+
SnapManager consente di suddividere un clone di un database.


