---
permalink: unix-installation-7mode/delete_reference_trademark.html 
sidebar: sidebar 
keywords: trademark 
summary: Informazioni sul marchio 
---
= Informazioni sul marchio
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


NetApp, il logo NetApp , Vai oltre, Più veloce, AltaVault, ASUP, AutoSupport, Campaign Express, Cloud ONTAP, Clustered Data ONTAP, Customer Fitness, Data ONTAP, DataMotion, Fitness, Flash Accel, Flash Cache, Flash Pool, FlashRay, FlexCache, FlexClone, FlexPod, FlexScale, FlexShare, FlexVol, FPolicy, GetSuccessful, LockVault, Gestisci ONTAP, Mars, MetroCluster, MultiStore, NetApp Insight, OnCommand, ONTAP, ONTAPI, RAID DP, RAID-TEC, SANtricity, SecureShare, Simplicity, Simulate ONTAP, Snap Creator, SnapCenter, SnapCopy, SnapDrive, SnapIntegrator, SnapLock, SnapManager, SnapMirror, SnapMover, SnapProtect, SnapRestore, Snapshot, SnapValidator, SnapVault, StorageGRID, Tech OnTap, Unbound Cloud, WAFL e altri nomi sono marchi commerciali o marchi registrati di NetApp, Inc., negli Stati Uniti e/o in altri paesi. Tutti gli altri marchi o prodotti sono marchi commerciali o marchi registrati dei rispettivi titolari e devono essere trattati come tali.  Un elenco aggiornato dei marchi NetApp è disponibile sul Web all'indirizzo http://www.netapp.com/us/legal/netapptmlist.aspx[] .
