---
permalink: unix-installation-7mode/task_verifying_database_backups.html 
sidebar: sidebar 
keywords: verifym backup, database, backed-up, file, corrupt, unix 
summary: È possibile verificare il backup del database per assicurarsi che i file di cui è stato eseguito il backup non siano corrotti. 
---
= Verifica dei backup del database
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile verificare il backup del database per assicurarsi che i file di cui è stato eseguito il backup non siano corrotti.

Se durante la creazione di un backup non è stata selezionata la casella di controllo *verify backup using the Oracle DBVERIFY utility* (verifica backup mediante l'utility Oracle DBVERIFY*), è necessario eseguire questa procedura manualmente per verificare il backup. Tuttavia, se si seleziona la casella di controllo, SnapManager verifica automaticamente il backup.

. Nella struttura *Repository*, selezionare il profilo.
. Fare clic con il pulsante destro del mouse sul backup che si desidera verificare e selezionare *Verify* (verifica).
. Fare clic su *fine*.
+
Se l'operazione non riesce, fare clic su *Dettagli operazione* per visualizzare le cause dell'errore dell'operazione.

+
Nella struttura *Repository*, fare clic con il pulsante destro del mouse sul backup, quindi fare clic su *Proprietà* per visualizzare i risultati dell'operazione di verifica.



È possibile utilizzare i file di backup per eseguire operazioni di ripristino. Per informazioni su come eseguire operazioni di ripristino utilizzando l'interfaccia utente di SnapManager, consultare la _Guida in linea_. Se si desidera utilizzare l'interfaccia della riga di comando (CLI) per eseguire operazioni di ripristino, consultare la _Guida all'amministrazione di SnapManager per Oracle per UNIX_.

*Informazioni correlate*

https://library.netapp.com/ecm/ecm_download_file/ECMP12471546["Guida all'amministrazione di SnapManager 3.4 per Oracle per UNIX"]
